### ISSUE TITLE
MFA Hierarchy with Interconnect

### ISSUE THREAD

**Issue by justind417** [MilestoneSystemsInc/PowerShellSamples#10]
Hey Josh,

When working with the powershell tools in an MFA Environment that also uses Interconnect, what is the best way to get interconnected camera device information? For example, following the samples - 

foreach($hardware in Get-Hardware -RecordingServer $rec){
                $enabledCameras = $hardware | Get-Camera | Where-Object Enabled
                        $row = New-Object -TypeName PSObject
                         $row | Add-Member -MemberType NoteProperty -Name Name -Value $enabledCameras.Name
                         $row | Add-Member -MemberType NoteProperty -Name Enabled -Value $enabledCameras.Enabled
                         $row | Add-Member -MemberType NoteProperty -Name RecordingServerName -Value $rec.Name
     
                         $hardwareInfo.Add($row)
                         }

When an interconnected hardware device is reached, the scripts outputs the following in the csv: "System.Object[] | System.Object[]"

If I missed something in the documentation regarding interconnect, please let me know. 

Appreciate your time!

Justin

**Comment by jhendricks123** [comment]
Hi Justin, it might depend a little on what kind of information you're trying to retrieve from the remote site. For example, you won't be able to retrieve the camera's MAC or actual physical IP through a property of the interconnected hardware, but you could get that information directly from the remote site. When you view that information through interconnect, you're basically just going to see the address of the remote management server.

Other than that, there's no difference between a standard IP camera or encoder, and an interconnected site, when you're combing through the hardware/devices attached to a system. So you should be able to get the same basic information when looking at an interconnect "device" compared to looking at an Axis, Bosch, Sony, etc.

The way you're building your rows and adding them to a list, it looks like you're creating an array of "enabled cameras" and then instead of enumerating through each of the cameras attached to that hardware device, you're accessing the Name and Enabled properties on that list. The result is going to be an array of names and booleans, and you're adding those arrays of names all to a single row.

My guess is that if you have/had any other multi-channel camera, you would see the same phenomena. Here's what I would do to build that list:

```powershell
$hardwareInfo = New-Object System.Collections.Generic.List[pscustomobject]
foreach ($rec in Get-RecordingServer) {
  foreach ($hardware in $rec | Get-Hardware | Where-Object Enabled) {
    foreach ($camera in $hardware | Get-Camera | Where-Object Enabled) {
      $row = [pscustomobject]@{
        Name = $camera.Name
        Enabled = $camera.Enabled # We know it's enabled though because we're filtering for this already
        RecordingServerName = $rec.Name
        SomeOtherProperty = $WhateverWouldBeUsefulToInclude
      }
      $hardwareInfo.Add($row)
    }
  }
}
```

But if you want to instead enumerate through sites using MFA instead, you could do so but you'll end up with some duplication since you'll count your interconnect "devices" as well as the sites those interconnect devices represent. You could filter out the interconnect devices by looking at their driver though in your Get-Hardware | Where-Object filter. To enumerate through MFA sites you could do...

```powershell
foreach ($site in Get-Site -ListAvailable) {
  $site | Select-Site
  foreach ($rec in Get-RecordingServer) {
    # Insert the same blocks from above in here
  }
}
```
