### ISSUE TITLE
get-vmsCamera -Name "xxx" failed with no ascii camera name

### ISSUE THREAD

**Issue by jiemjiem** [MilestoneSystemsInc/PowerShellSamples#104]
I have a issue with non ascii camera names (like "caméra1" instead of "camera1")
get-VmsHardware -Name  works fine but get-VmsCamera -Name failed.

**Comment by Tarterman** [comment]
What version of MilestonePSTools are you using?  I just tried it on my system and it worked fine.  I'm running the latest version of 23.2.1.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/42384254/aaa41537-7ac3-4046-bfa7-c89cf8d32a39)

I tried it on an OS that is running in Spanish thinking maybe it was related to the OS language but it worked fine there also.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/42384254/17cd3a19-8a2d-4d4d-9dc3-5dddb18b990f)

I would make sure you are running the latest version of MilestonePSTools, just to rule that out.  If you still have issues, is it failing in the sense that it isn't returning a result or is it throwing an error?  If it is throwing an error, can you provide the error?

**Comment by jiemjiem** [comment]
milstonepstools: 23.2.1
Get-VmsCamera -Name "ééé" return Exception   "Invalid Text Value"
_MilestonePSTools.psm1:3832 : 41
+ ....foreach($result in $queryService.Query($cameraFilter, $MaxResults)) {
    +CategoryInfo : NOt Specified (:) [], MethodInvocationException_

**Comment by Tarterman** [comment]
@joshooaj, do you have any thoughts?  I tried this against my 2023 R2 English system, 2022 R3 Spanish OS system, and even a 2019 R3 English system and it works on all of them.

**Comment by joshooaj** [comment]
Strange, I can't reproduce it either. I was going to say that it may be that the Configuration API on the management server has been fixed to handle non-ASCII characters better since version 2020 R3 but if you tested it on 2019 R3 that seems unlikely.

The problem is associated with the `VideoOS.ConfigurationApi.ClientService.QueryItems` class and/or the Configuration API endpoint on the management server responsible for executing the query which is something we don't have visibility into from the MilestonePSTools project - it's maintained by our core MIP SDK team. I'll take a quick look at the source and ask them about it though.
