### ISSUE TITLE
request for method to add camera event

### ISSUE THREAD

**Issue by jiemjiem** [MilestoneSystemsInc/PowerShellSamples#105]
hello
Could you add new methods to add events on camera? (camera "event" tab in milestone) 
Thanks

**Comment by joshooaj** [comment]
Hi @jiemjiem,

Solid request - I would definitely like have those commands in the module. I'll aim to add it for 23.2.3. We're about to publish 23.2.2 with new connection-related commands introducing "named connection profiles" that are persisted to your local user profile so that you don't have to explicitly logon every time you use the module, as well as commands for configuring webhooks.

There are also some neat improvements under the hood with custom attributes used to improve error messaging around version and feature requirements, as well as update the docs based on those declared requirement attributes.

Here are the new commands coming up:

- Connect-Vms
- Disconnect-Vms
- Get-VmsConnectionProfile
- Get-VmsWebHook
- New-VmsWebHook
- Remove-VmsConnectionProfile
- Remove-VmsHardware
- Remove-VmsWebHook
- Save-VmsConnectionProfile
- Set-VmsWebHook
- Test-VmsConnection

Until some cmdlets for working with hardware based events are introduced, you can access these from the existing Camera (or mic, or input, etc) objects. For example, here is a script to enable all inputs on the selected hardware, and add/enable all the events available on those inputs (input rising/falling for example).

```powershell
Connect-ManagementServer -ShowDialog -AcceptEula -Force
$hardwares = Get-VmsHardware | Out-GridView -OutputMode Multiple -Title "Enable input and rising/falling events on selected hardware"

foreach ($hardware in $hardwares) {
    foreach ($inputEvent in $hardware | Get-Input) {
        if (-not $inputEvent.Enabled) {
            Write-Host "Enabling input $($inputEvent.Name) on $($hardware.Name)"
            $inputEvent.Enabled = $true
            $inputEvent.Save()
        }
        $hardwareDeviceEvents = $inputEvent.HardwareDeviceEventFolder.HardwareDeviceEvents[0]
        $dirty = $false
        foreach ($eventItem in $hardwareDeviceEvents.HardwareDeviceEventChildItems) {
            if (-not $eventItem.EventUsed) {
                Write-Host "Adding $($eventItem.DisplayName) to input $($inputEvent.Name) on $($hardware.Name)"
                $eventItem.EventUsed = $true
                $dirty = $true
            }
            if (-not $eventItem.Enabled) {
                Write-Host "Enabling $($eventItem.DisplayName) for use on input $($inputEvent.Name) on $($hardware.Name)"
                $eventItem.Enabled = $true
                $dirty = $true
            }
        }
        if ($dirty) {
            $hardwareDeviceEvents.Save()
        }
    }
}
```

**Comment by joshooaj** [comment]
Hi @jiemjiem 

I'm exploring ideas for commands to add/remove events on all devices - hardware, cams, mics, speakers, metadata, and IO. Do you have any ideas about how you would expect to work with them in PowerShell?

Events on all of these devices are accessed the same way, so I'm tempted to have Get-VmsDeviceEvent and Set-VmsDeviceEvent.

The commands work well for getting all available events on a device, whether they're "Used" which means they've been "added" in the management client, whether they're "Enabled" meaning they're added, AND enabled, and you can modify those properties with the Set command.

I like the idea of a single pair of commands for this, but I'm betting most users will look for a command like "Add/Remove-VmsCameraEvent" or similar. Maybe we could have a single command pair, but create aliases to point "Get-VmsCameraEvent" to "Get-VmsDeviceEvent" for example?

**Comment by jiemjiem** [comment]
Hi, In  my case I only need to add the event "operations" to all my axis cams. Sorry I don't know if there is a difference between "device events" and "cam events" and  I hope to be able to do it in 2020R3 release...

**Comment by joshooaj** [comment]
I believe we're taking about the same events - the place in Management Client when looking at a camera, there's an Events tab, and you can click "Add" to add that camera-based event to Milestone?

This capability wasn't added to the configuration api until 2021 R1 so even though you can use a newer MilestonePSTools version, the server needs to support the API request. So you'll need to upgrade your VMS version to automate configuration of camera-based events.
