### ISSUE TITLE
Get/Set VmsOverallSecurity Not setting permissions 

### ISSUE THREAD

**Issue by MDDacha** [MilestoneSystemsInc/PowerShellSamples#109]
Hi , 

I'm using 23.2.2 I can see in the change log that some changes have happened to to GetVmsroleOverallsecurity and SetVmsroleOverallsecurity 

When setting the overall security it returns the below error 

> Get-VmsRole : Cannot process argument transformation on parameter 'Id'. Cannot convert the 
> "VideoOS.Platform.Proxy.ConfigApi.ConfigurationItemPath" value of type 
> "VideoOS.Platform.Proxy.ConfigApi.ConfigurationItemPath" to type "System.Guid".
> At C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\23.2.2\MilestonePSTools.psm1:12694 
> char:37
> +             $Role = Get-VmsRole -Id $roleId
> +                                     ~~~~~~~
>     + CategoryInfo          : InvalidData: (:) [Get-VmsRole], ParameterBindingArgumentTransformat 
>    ionException
>     + FullyQualifiedErrorId : ParameterArgumentTransformationError,Get-VmsRole
>  
> Set-VmsRoleOverallSecurity : You cannot call a method on a null-valued expression.
> At line:2 char:1
> + Set-VmsRoleOverallSecurity -Permissions $permissions
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : InvalidOperation: (:) [Write-Error], RuntimeException
>     + FullyQualifiedErrorId : InvokeMethodOnNull,Set-VmsRoleOverallSecurity

Below is the script I'm using also 

$permissions = Get-VmsRoleOverallSecurity -Role 'Operators' -SecurityNamespace Cameras
$permissions.GENERIC_READ = 'Allow'
$permissions.VIEW_LIVE = 'Allow'
$permissions.PLAYBACK = 'Allow'
$permissions.EXPORT = 'Deny'
Set-VmsRoleOverallSecurity -Permissions $permissions

**Comment by joshooaj** [comment]
Hi @MDDacha,

Thanks for the bug report! The test automation didn't pick it up because each `Set-VmsRoleOverallSecurity` test case was piping the role in instead of letting `Set-VmsRoleOverallSecurity` retrieve a fresh role object using the value in `$permissions.Role`.

I've fixed it and added a new test case to make sure we catch it in the future. Until MilestonePSTools v23.2.3 is published, you can work around the bug using a more performant version of your script where we only retrieve the role object once and re-use it:

```powershell
$role = Get-VmsRole -Name 'Operators'
$permissions = $role | Get-VmsRoleOverallSecurity -SecurityNamespace Cameras
$permissions.GENERIC_READ = 'Allow'
$permissions.VIEW_LIVE = 'Allow'
$permissions.PLAYBACK = 'Allow'
$permissions.EXPORT = 'Deny'
$role | Set-VmsRoleOverallSecurity -Permissions $permissions
```
