### ISSUE TITLE
Set-VmsCameraStream  capital letter or not in settings parameters 

### ISSUE THREAD

**Issue by jiemjiem** [MilestoneSystemsInc/PowerShellSamples#112]
Hello, 
I have difficulties to guess correct settings values  in Set-VmsCameraStream() 
some of them requiere values with capital letter, other requiere strict lowercase values.
For example:
--------------------CorrectValue-------IncorrectValue (method failed)
ControlPriority:-----“None”------------“none “ 
ZGopMode:---------"fixed”------------"Fixed”
ControlMode:----“ConstantBitRate”----“constantbitrate”
MaxGopMode:------“custom”-----------“Custom”

Warning: the real syntax is checked only when the value needs to be changed in MIlestone.
A global rule (case insensitive for example) would be great in future versions.
Jiem

**Comment by joshooaj** [comment]
Hi @jiemjiem,

The stream and general setting property "keys" and their values are provided by, and validated by the MIP SDK (sometimes locally, and sometimes by the server depending on the context I think).

We _could_ complicate the PowerShell module by checking each setting before we pass your value to MIP SDK to see if we can figure out the type of parameter, whether the provided value is valid, and try to retrieve the value with the correct capitalization for string values with a fixed set of options, but all that checking would add potential failures, and a small amount of processing time which might add on systems with thousands of devices to update.

I know it's frustrating when you discover that a value needs to be "custom" instead of "Custom", especially when occasionally the same setting seems to accept a different value on two different cameras. The settings are provided by the device pack drivers and each driver can have a similar, or totally different set of properties depending on the camera. All we do with MilestonePSTools is leverage the MIP SDK to pass data to and from Milestone in a more PowerShell-friendly syntax.

By default, `Get-VmsCameraStream` returns the "Display" values - the values you're supposed to see in Management Client. So if you run `($camera | Get-VmsCameraStream -LiveDefault).Settings` you'll get a hashtable where the keys are the stream property names and the values are the "Display" values.

You can instead run `($camera | Get-VmsCameraStream -LiveDefault -RawValues).Settings` and you'll see the current internal "raw" values for the same settings - the values that the SDK expects when we want to change them.

You can also access the "ValueTypeInfo" for each property which will give you information about the names and values for each option for a given setting. For example...

```powershell
$camera = Select-Camera
$stream = $camera | Get-VmsCameraStream -LiveDefault

$stream.Settings
$stream.ValueTypeInfo.ControlMode
```

returns...

```plaintext
$stream.Settings

Name                           Value
----                           -----
FPS                            10
ControlMode                    Variable bit rate
StreamReferenceId              28DC44C3-079E-4C94-8EC9-60363451EB41
MaxGOPMode                     Default (determined by driver)
StreamingMode                  RTP/RTSP/TCP
TargetBitrate                  2000
ControlPriority                None
MaxGOPSize                     30
Codec                          H.264
IncludeTime                    No
EdgeStorageSupported           true
IncludeDate                    No
Resolution                     1280x960
Compression                    30

TranslationId                        Name              Value
-------------                        ----              -----
5bc9bfa3-0fcc-46f3-93dd-5b9b61f9a431 Variable bit rate VariableBitRate
92252761-989f-4635-9471-c116892d0904 Constant bit rate ConstantBitRate
```

So using the ValueTypeInfo hashtable, you can inspect the options for settings that require you to select from a list and the `Value` column will contain the values the Management Server expects. It will also help you understand the range of supported values when FPS or bitrate must fall between two numbers, sometimes with a given "step value" like increments of 1 or 5 for example.

**Comment by joshooaj** [comment]
Hi @jiemjiem,

Thanks for the inspiration - I just published a new blog post on working with stream settings! Hopefully it helps explain the way device settings in MIP SDK work and how to discover the values expected by the management server.

[All About Stream Settings](https://www.milestonepstools.com/blog/2023/10/31/all-about-stream-settings/)
