### ISSUE TITLE
New-VmsRole

### ISSUE THREAD

**Issue by Jaffe1986** [MilestoneSystemsInc/PowerShellSamples#120]
Just a heads-up, I was working on a script that creates new customers. I was running through ..

New-VmsDeviceGroup -Name $  -Description $

New-VmsViewGroup -Name $  -Description $

New-VmsRole -Name $  -Description $

I noticed I was getting 2 view groups, one with a description and one without. I ran through each line and I found that New-VmsRole also creates a ViewGroup.

I was able to account for this in the end but I noticed that the New-VmsRole documentation does not say that it is also creating a view group.

**Comment by Tarterman** [comment]
@Jaffe1986, the reason New-VmsRole creates a view group named after the Role is because that is what happens when you create a role in the Management Client (and what the APIs automatically do).

I'll tag @joshooaj so he can look at putting a note in the documentation so it is indicated that it does that. Thanks for the suggestion.

**Comment by joshooaj** [comment]
Thanks @Tarterman that's exactly what's happening! There is no code in that cmdlet to create a viewgroup - the management server does it whether you want it to or not. I'll be sure to publish a note in the docs about it soon, thanks for the head up @Jaffe1986 🙏🏼
