### ISSUE TITLE
VMSCameraGeneralSetting not applying (Rotation/Mirror)

### ISSUE THREAD

**Issue by mrilanduk** [MilestoneSystemsInc/PowerShellSamples#122]
We believe we may of discovered a bug/Issues when trying to set rotation and Mirror using the Set-VMSCameraGeneralSetting.
Settings is being passed and change is visible within the application however no change to the image rotation or mirror.

**Comment by joshooaj** [comment]
What Milestone XProtect version and MilestonePSTools version are you using?

This sounds familiar - I believe on some XProtect versions the validation is slightly broken and you're allowed to set a value to the "Display Value", or the value shown in the UI. But then the recording server doesn't do anything with the value because it isn't valid. For example, I think in some cases the management server will allow you to set the codec to "H264" even though the expected value is "h264".

Depending on the camera, there might be a difference between the raw values and the display values for the rotation/mirror options. For example, If a display value for MirrorImage is "Yes", the raw value might be "yes", and maybe the server is allowing the uppercase Y when it shouldn't, resulting in an invalid state where the new value shows up in the UI but isn't pushed to the camera.

Can you show the output of the command below? Change "MirrorImage" as needed based on the property names for your particular cameras. The "Name" column is the display name and the Value column is the value you should be sending with the "Set" command.

Sometimes you will only/also see entries like MinValue, MaxValue, and optionally StepValue which are used to help integrations understand the rules, if any, for a setting without fixed values. 

```powershell
$camera = Select-Camera
($camera | Get-VmsCameraGeneralSetting -ValueTypeInfo).MirrorImage
```

**Comment by mrilanduk** [comment]
Xprotect v23.2a PSTools v23.3.1
![Screenshot 2024-02-22 085210](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/87877771/81e8351c-36b3-4d16-8aa0-87ae0a37f986)

**Comment by aoforb** [comment]
@joshooaj this is very helpful thank you. 
So based on what you said, the variable for `Rotation 180, mirror` is `5` and not the string contained in Name column.

**Comment by joshooaj** [comment]
Closing stale issue.

_Note: The issue was identified and resolved for a future XProtect release - hopefully 2024 R1_
