### ISSUE TITLE
Disabling motion detection for a camera

### ISSUE THREAD

**Issue by maxmantis** [MilestoneSystemsInc/PowerShellSamples#125]
We are trying to enable/disable motion detection for a camera with MilestonePSTools, but are running into issues and hope you can help us. We are using MilestonePSTools version 23.3.1 and XProtect 2023 R3 with an Express+ license.

We first tried to use the `Set-VmsCamera` or `Set-VmsCameraGeneralSettings` but could not find the option to set motion detection with either of the methods. If I understand correctly, the parameters that can be changed with `Set-VmsCamera` are limited to the method parameters, while `Set-VmsCameraGeneralSettings` is limited to the settings which are available via `Get-VmsCameraGeneralSettings`.

We then had a look at the [PowerShell Gallery](https://www.powershellgallery.com/packages/MilestonePSTools/23.3.1/Content/MilestonePSTools.psm1) and, by piecing together bits of `Get-VmsCameraReport` and `Set-VmsCamera`, put together the following to disable motion detection for our `Camera01`:
```
$camera = Get-VmsCamera -Name 'Camera01'
$camera.MotionDetectionFolder.MotionDetections[0].Enabled = $false
$camera.Save()
```
However, when checking in the Management Client, motion detection is still enabled and when reloading the camera and checking the value with 
```
$camera = Get-VmsCamera -Name 'Camera01'
$camera.MotionDetectionFolder.MotionDetections[0].Enabled
```
the change is not persistent.

Are we missing something here and/or could this functionality be introduced in a future version? Thanks for your help!

**Comment by joshooaj** [comment]
Hi @maxmantis,

Sorry that you had to hunt down how to change motion detection settings, but nice job digging into the `MotionDetectionFolder` and finding what you needed. You're very close - it's only because of the way our strongly-typed configuration api objects are designed that it didn't work.

Try this instead:

```powershell
$camera = Get-VmsCamera -Name 'Camera01'
$motion = $camera.MotionDetectionFolder.MotionDetections[0]
$motion.Enabled = $false
$motion.Save()
```

There are two reasons why the example you provided didn't work in case it helps in other areas of the module or MIP SDK:

## Call `Save()` on the closest Item

The `MotionDetections` object is it's own "configuration item" which means we should call `.Save()` directly on it instead of the camera. You might expect that the motion settings are a camera property, or that at least calling `Save()` on the camera would automatically save changes to child items but it doesn't.

This isn't the easiest aspect of the configuration api to explain, but basically there are ~3 kinds of configuration "items". There are "Items", "Child Items", and "Folders".

It's only valid to call the `Save()` method on Items, and doing so will only persist the properties of that Item. To make things more confusing, some Items, like the `DeviceDriverSettings` Item at `$camera.DeviceDriverSettingsFolder.DeviceDriverSettings[0]` have "Child Items" directly attached to the object instead of nested under a "Folder". In that case, when you change a property of a Child Item, you would call `Save()` on the parent to push that change to the Management Server. For example...
   
```powershell
$camera = Get-VmsCamera -Name Camera01
$settings = 
$camera.DeviceDriverSettingsFolder.DeviceDriverSettings[0]
$settings.DeviceDriverSettingsChildItem.Properties.SetValue('EdgeStorageEnabled', 'False')
$settings.Save()
```

## Strongly typed objects have bad short-term memory

When the configuration api was originally introduced, it only provided a generic hierarchy of "ConfigurationItem" objects. Some ConfigurationItems were cameras or recording servers, some ConfigurationItems were folders containing device group and device collections, but everything was just a `ConfigurationItem`.

Eventually we added "strongly typed" items so that .NET developers could work with `Camera`, `Hardware`, and `RecordingServer` objects which made code easier to read. But all these objects are is a thin wrapper around the original configuration item. Every time you "dot" into an object like `$camera.MotionDetectionFolder.MotionDetections[0]`, the MIP SDK creates a brand new `MotionDetection` object based on the underlying generic `ConfigurationItem`. So if you "dot" into the motion detection settings to change a value, then you "dot" into it again to call the `Save()` method, you already lost the change you made because it was made on a version of the object that doesn't exist anymore, and changes aren't persisted to the underlying ConfigurationItem unless you call `Save()` on the exact same instance of that object.

```powershell
$camera = Get-VmsCamera -Name Camera01

# This won't work because the second time we access MotionDetections[0]
# we're given a brand new copy of the original motion settings
$camera.MotionDetectionFolder.MotionDetections[0].Enabled = $false
$camera.MotionDetectionFolder.MotionDetections[0].Save()

# This works because we save a reference to the motion settings
# object to a variable, then modify and call Save() on the same variable
$motion = $camera.MotionDetectionFolder.MotionDetections[0]
$motion.Enabled = $false
$motion.Save()

# This works too - it's a little weird since there's only ever one
# MotionDetection object in the collection, but just like the previous 
# example, we modify and call Save() on the exact same reference
$camera.MotionDetectionFolder.MotionDetections | ForEach-Object {
  $_.Enabled = $false
  $_.Save()
}
```

**Comment by maxmantis** [comment]
Thanks for the detailed answer and the context, appreciate it! Also, I can confirm that `$motion.Save()` did the trick and we now have something that works for us.
