### ISSUE TITLE
Set-ManagementServerConfig -Force

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#13]
Hello,

I know we can do `Set-ManagementServerConfig -Confirm:$false` but I think `Set-ManagementServerConfig -Force` would be cleaner and more consistent with the other powershell APIs.

**Comment by jhendricks123** [comment]
Force and Confirm are intended for different purposes. Force is a parameter you usually use when you know something exists or it is read-only and you want to overwrite it anyway, while Confirm is recommended to use whenever the operation is going to change the state of the system in an important or potentially risky way.

Confirm is part of PowerShell's common parameters for cmdlets and works based on the interaction of the $ConfirmPreference variable and ConfirmImpact value of the cmdlet. If $ConfirmPreference is Medium and the cmdlets impact is High, you'll have to explicitly confirm by setting -Confirm:$false or acknowledging the prompt.

Registration involves potentially updating *Config.xml, stopping and getting services, and runs the risk of making a working VMS less functional if something fails during the process. If the recorder is working and doing recordings already, it means recording will be disrupted and if running on the management server it means users will be unable to login briefly (or for a prolonged period if someone went wrong). For those reasons I think setting the ConfirmImpact to High makes sense.

I believe you can set $ConfirmPreference to High in a script and then you don't have to supply a value in the Confirm parameter. But is there a compelling reason to also use (or require) the Force parameter?

Under what circumstances would the Force parameter be required? All? Only if the server is already registered? There's no good way for me to know if the server is currently successfully registered for not. I could look for the IDP.sec file, but that just tells me it was registered previously, not that it is currently registered and functional.

In Remove-Hardware I require Force all the time because it will result in irreversible loss of data. In hindsight I probably should have used ConfirmImpact there instead. But either way it has the intended effect of making the user double check what they're doing is what they intended.

Sorry if I'm being too pedantic here. Apparently this can become quite a debate lol... there's a few links on this topic below - let me know what you think? My goal is to try to stick as close to Microsoft recommended usage, but I've only been doing PowerShell for a little under two years and might be misunderstanding/misinterpreting things.

https://stackoverflow.com/questions/34749333/powershell-guidelines-for-confirm-force-and-whatif#:~:text=%2DForce%20means%20%22force%20overwrite%20of,%2Donly%20file%20system%20attribute%22.&text=%2DConfirm%20and%20%2DForce%20are%20not,with%20the%20read%2Donly%20attribute.

https://github.com/Azure/azure-powershell/issues/475

**Comment by Silex** [comment]
Ha, I think it's hard to argue against such a well reasoned answer. Thanks for taking the time :+1:
