### ISSUE TITLE
Add-VmsHardware not adding Camera

### ISSUE THREAD

**Issue by aoforb** [MilestoneSystemsInc/PowerShellSamples#135]
Hello,

version: milestonepstools.23.3.1

Apologies for the masking. 

The variable `$camera.Name` contains a name that is not in the list from `Get-VmsHardware`, also the camera IP address .133 is not currently on the recording server. Yet the warning suggests otherwise.

Does anyone know why? Seem to have the same problem on the Xprotect management UI too.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/146780854/783ded05-ea38-454c-b95a-0978bfbde13b)

**Comment by Tarterman** [comment]
@aoforb, since you are seeing the same thing in the Management Client also, I would try the steps in this KB:

https://supportcommunity.milestonesys.com/s/article/cannot-add-device-error-failed-to-add-hardware-it-already-exists-troubleshooting?language=en_US

If that doesn't resolve it, I would suggest reaching out to tech support so they can dig in further.

**Comment by aoforb** [comment]
Thanks, will continue with tech support.
