### ISSUE TITLE
For Get-VmsCameraReport command, is there a way to prevent the following error message processing?

### ISSUE THREAD

**Issue by tobitanaka** [MilestoneSystemsInc/PowerShellSamples#137]
For Get-VmsCameraReport command, is there a way to prevent the following error message processing? since:
* The cause of the error message is known and the customer has decided not to implement a solution (kept as a known issue)
* The processing took about a minute while communicating with the Recording Server via 7563/TCP
* The customer understood that 'Get-VmsCameraReport -ErrorAction SilentlyContinue' can prevent the error output to the console but did not skip its processing

* The error message appeared was as follows (Original is Japanese and translated to English message as follows):

----
Exception occurred while calling “GetVideoDeviceStatistics” with “2” arguments: “Unable to connect to remote server.”
Occurrence location Line:1 Character:1

+ Get-VmsCameraReport

+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-VmsCameraReport
Exception occurred while calling “GetVideoDeviceStatistics” with “2” arguments: “Unable to connect to remote server.”
Occurrence location Line:1 Character:1
+ Get-VmsCameraReport

+ CategoryInfo : NotSpecified: (:) [Write-Error], WriteErrorException
+ FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-VmsCameraReport
----

**Comment by Tarterman** [comment]
@tobitanaka, I can't think of a way to do it without excluding the entire Recording Server which would also mean that you won't get any details regarding cameras on that Recording Server.

Maybe it's something that @joshooaj could look at adding a parameter to exclude running that or maybe something where, if it fails on the first camera for a Recording Server because it can't connect then it just skips the rest of the cameras on that Recording Server with a message indicating so or something else.

**Comment by tobitanaka** [comment]
@Tarterman 
Thank you for the update, understood the status and
I will ask @joshooaj as follows:
@joshooaj , it is appreciated that any measure for this query may be appreciated should there be.

**Comment by tobitanaka** [comment]
Since there may not have workaround to this case issue, the user has agreed to close this issue, this ticket was closed accordingly, thank you @Tarterman and @joshooaj
