### ISSUE TITLE
ERROR Updating Vmshardware in Milestone XProtect

### ISSUE THREAD

**Issue by Klaver-Que** [MilestoneSystemsInc/PowerShellSamples#139]
I used the PowerShell command " Import-VmsHardware -RecordingServer <my recording server> -path "C:\path\CSV_file.csv"  to import hardware into my milestone VMS,

But then I needed to adjust the hardware/camera names,and so I followed the same procedure with a hope that it will just do an update of the camera names as long as the ip addresses are the same, but to my surprise, I get an error:

 Add-VmsHardware : Add-VmsHardware failed with error code 60276. VMO60276: Could not add the hardware.

The hardware is already defined on the recording server.

At C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\24.1.5\MilestonePSTools.psm1:5323 char:21

...                    Add-VmsHardware [u/params](https://www.reddit.com/user/params/) -Force -SkipConfig | Forea ...

+                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException

FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Add-VmsHardware 

Could someone help

**Comment by Tarterman** [comment]
@Klaver-Que, you can try [VmsImportHardwareExcel](https://www.milestonepstools.com/tools/import-hardware-from-excel/) that will export everything and then let you make changes and import it back in. There is a lot of information on the page to help with that.

If you haven't already done a lot of configuration on the cameras you have imported, another option would be to just delete everything from the Recording Server and add it back in again.

**Comment by joshooaj** [comment]
Hi @Klaver-Que,

We released a new version of MilestonePSTools with updated versions of `Import-VmsHardware` and `Export-VmsHardware`. I hope this solves your problem (or that it will the next time you need to do an update like this). I'll close this issue but please let us know if you have any other questions or issues!

## Changes

- The CSV file format has been improved - all devices are now represented on their own row in the file which makes for much easier editing when you have multi-channel devices or you want to enable/name metadata, microphones, and other device types.
- You can use `Import-VmsHardware` to update names of existing hardware/devices by adding the `-UpdateExisting` switch.
- You can perform a much more detailed export, and also import/update devices from an Excel file. When you export with `Export-VmsHardware`, specify a file with a `.xlsx` extension instead of `.csv`.
