### ISSUE TITLE
Get-Snapshot fails to scale images

### ISSUE THREAD

**Issue by cvanderbles** [MilestoneSystemsInc/PowerShellSamples#144]
When undergoing testing with Get-Snapshot, I have found that the -Height and -Width tags are not respected.  This results in images that are still exportable, but only at full, native resolution.  Tested with the following command $Path variable shown instead of my actual path):

Connect-ManagementServer -AcceptEULA -ShowDialog
$camera = Select-Camera -SingleSelect
$null = $camera | Get-Snapshot -Height 640 -Live -KeepAspectRatio -Save -Path $Path -UseFriendlyName

Result is successful snapshot export, but at full resolution.  Unable to test -KeepAstectRatio or -IncludeBlackBars tags as a result.  Also tested without the -KeepAspectRatio tag and with trying to set -Width instead of -Height

Milestone XProtect Corporate 2023R3, MilestonePSTools Version 24.1.5

**Comment by Tarterman** [comment]
@cvanderbles, using the width/height parameters is a little confusing because you have to specify width and height but the command doesn't validate that you have specified both if you have specified only one.

So, if you specify both and specify -KeepAspectRatio, then it will ignore one of the values you specified in order to maintain the aspect ratio.

Here is an example:
![image](https://github.com/user-attachments/assets/8d9a3b9a-0bdc-482b-b1a8-41e2679e2eb4)

You can see I specified the Width as 320 and the Height as 240 and I also specified KeepAspectRatio. Since this camera is a 16:9 aspect ratio, you can see in the output that it changed the Height to 180 in order to maintain the aspect ratio.

**Comment by cvanderbles** [comment]
Interesting, I can confirm this behavior.  Since this get's me 95% resolved, I'm good, but I would probably change my bug/request for documentation/clarification as to which parameter will get ignored when KeepAspectRatio is called (is it always width?, is it always the larger of the two values?  is it kept based on the order in which invoked?, etc.).  Additionally, I would recommend modifying the Get-Snapshot function to work when only one of the two parameters is called so long as KeepAspectRatio is also called.

**Comment by Tarterman** [comment]
Thanks for the feedback @cvanderbles.

@joshooaj, see cvanderbles last comment regarding feedback in regards to the Get-Snapshot cmdlet.

**Comment by joshooaj** [comment]
Thanks @cvanderbles, I appreciate the feedback! It's definitely on my radar to write a new `Get-VmsSnapshot` cmdlet. There's a lot of room for improvement.

At the moment we're adding some LPR-related cmdlets, and then working on either improving or rewriting the `Import-VmsHardware` and `Export-VmsHardware` cmdlets. I'll make sure the snapshot cmdlet is on the todo list.
