### ISSUE TITLE
Camera Resolution

### ISSUE THREAD

**Issue by jdennis319** [MilestoneSystemsInc/PowerShellSamples#147]
Hello,

I currently have 3k cameras running in Milestone and soon to have 47k. What would be the quickest way to adjust their resolution for the 3k cameras I have running in Milestone? Currently, they are all over the place, but I have implemented a standard that all cameras must be 1280x720 with a 6 FPS. 

Thanks for your help on this. 

Jeremy

**Comment by milestone-jh** [comment]
Hi Jeremy! You're looking for the `Get-VmsCameraStream` and `Set-VmsCameraStream` cmdlets, but there are some nuances when it comes to stream settings. Try running the following against one camera to list the available resolution options since the `Resolution` stream property is typically an `enum` value meaning there's a fixed list of resolution choices and you need to pick a value from the list. So I would probably go through all enabled cameras with `Get-VmsCamera`, use `Get-VmsCameraStream` and verify that the "1280x720" resolution value is available in the list of `ValueTypeInfo`s, and if so, update the resolution using `Set-VmsCameraStream`.

## Exploring the ValueTypeInfo's for the `Resolution` setting
```powershell
# Show a camera picker dialog to select a camera to test with
$camera = Select-Camera -SingleSelect

# Retrieve the stream properties for the current default live stream
$stream = $camera | Get-VmsCameraStream -LiveDefault

# Show the ValueTypeInfo records for the Resolution setting
$stream.ValueTypeInfo.Resolution
```

On my test camera, I get the following list of valid resolutions (only the first 5 are shown here):

```plaintext
TranslationId                        Name      Value
-------------                        ----      -----
9e523ae1-5b61-dc76-6f5c-818726881ecf 1920x1080 1920x1080
2e99c947-593d-c49b-5e84-400f878a4fc9 1280x960  1280x960
b7a6dd59-00cc-72e6-1f0d-3479c7e314ec 1280x800  1280x800
7e39f908-15d0-cbca-3fcb-1178fb9fa803 1280x720  1280x720
43193b0f-f671-a37d-8232-ab664190a125 1024x768  1024x768
```

The `Name` property represents the "display name" for the value and the `Value` property is what our API expects when you try to change the value. In the case of the `Resolution` setting, these usually match but keep that in mind for other settings - when there are `ValueTypeInfo` records describing the valid options, it's the string in the `Value` column you want to use in the next step.

## Updating the `Resolution` setting

If you're only updating one setting, it's not too ugly to do it in one line like this:

```powershell
$stream | Set-VmsCameraStream -Settings @{ Resolution = '1280x720' }
```

The `Set-VmsCameraStream` cmdlet accepts a `hashtable` with the setting names to update as keys. When you're updating more than one setting, it's cleaner to define your hashtable separately like this.

```powershell
$settings = @{
    Resolution = '1280x720'
    FPS        = 8
}
$stream | Set-VmsCameraStream -Settings $settings
```

Another alternative is to update the existing values in the `$stream.Settings` hashtable and pass that to `Set-VmsCameraStream` instead. If you do that, you want to use the `-RawValues` switch with `Get-VmsCameraStream`, otherwise the values in `$stream.Settings` will be the _display values_ and not the _raw values_.

```powershell
$stream = $camera | Get-VmsCameraStream -LiveDefault -RawValues
$stream.Settings.Resolution = '1280x720'
$stream.Settings.FPS = 8
$stream | Set-VmsCameraStream -Settings $stream.Settings
```

My `$stream.Settings` hashtable looks like this but yours will be different depending on the device make/model and device pack driver being used.

```plaintext
Name                           Value
----                           -----
ZFpsMode                       fixed
StreamReferenceId              28DC44C3-079E-4C94-8EC9-60363451EB40
StreamingMode                  TCP
ControlMode                    VariableBitRate
TargetBitrate                  2000
Compression                    30
Resolution                     1920x1080
FPS                            8.0
MaxGOPMode                     default
ControlPriority                None
IncludeTime                    no
EdgeStorageSupported           True
ZGopLength                     300
ZGopMode                       fixed
MaxBitrate                     0
MaxGOPSize                     30
ZStrength                      low
RetentionTime                  7
IncludeDate                    no
Codec                          h264
```

**Comment by jdennis319** [comment]
Thanks for this. I created this script below; however, it will only allow me to adjust one camera at a time. Can this be modified to change a group of cameras at a time or all of them? 



$camera = Select-Camera -SingleSelect

if ($null -eq $camera) {
    Write-Host "No camera selected, exiting..."
    exit
}


$stream = $camera | Get-VmsCameraStream -LiveDefault


$availableResolutions = $stream.ValueTypeInfo.Resolution
Write-Host "Available Resolutions:"
$availableResolutions | ForEach-Object {
    Write-Host ("Name: {0}, Value: {1}" -f $_.Name, $_.Value)
}


$resolutionValue = Read-Host "Enter the Value of the desired resolution from the list above"


if (-not ($availableResolutions | Where-Object { $_.Value -eq $resolutionValue })) {
    Write-Host "Invalid resolution value entered, exiting..."
    exit
}


$fpsValue = Read-Host "Enter FPS value (default is 8, press Enter to skip)" 

if ([string]::IsNullOrWhiteSpace($fpsValue)) {
    $fpsValue = 8  
}


$settings = @{
    Resolution = $resolutionValue
    FPS        = $fpsValue
}


$stream | Set-VmsCameraStream -Settings $settings

Write-Host "Resolution and FPS have been updated successfully."

**Comment by joshooaj** [comment]
Hi Jeremy,

Sure, you can use `Select-Camera -AllowFolders -AllowServers -RemoveDuplicates` if you want an interactive camera picker that will let you select one or more device groups or servers, and it will give you all the cameras within those groups recursively.

Or if you wanted to run this against all enabled cameras, you could wrap your script in a foreach loop like...

```powershell
foreach ($camera in Get-VmsCamera) {
    # Modify the stream settings for $camera here
}
```

**Comment by jdennis319** [comment]
Thank you, that worked out well!
