### ISSUE TITLE
Parallelism support

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#149]
Hello,

I wondered what would be the simplest way to get parallelism, ideally something like this:

``` powershell
Get-VmsCamera | Get-VmsCameraStream | Set-VmsCameraStream -Settings @{ FPS = 8 }
```

Currently I'm using a for loop on each camera, and I cannot help but feel this should be parallelizable...

**Comment by joshooaj** [comment]
Hi @Silex,

The _most_ performant way without switching to C# code is probably to use runspaces via a module like `Microsoft.PowerShell.ThreadJob` which gives you the `Start-ThreadJob` command. It works similar to the `Start-Job` command but with less overhead since it runs in the same process in another runspace vs launching a new powershell process and running in a separate process _and_ runspace.

Under most circumstances I haven't actually seen multithreading increase throughput enough to justify the added complexity. It seems like the management server serializes a lot of requests regardless of whether they're coming through the same WCF channel or unique WCF channels. But I haven't dug that deep into parallel performance for a couple of years so your mileage may vary.

I tried the following just now, and it just seems like the requests are deadlocked - they never complete.

```powershell
$jobs = Get-VmsCamera | Get-VmsCameraStream -Enabled | % {
    Start-ThreadJob -ArgumentList $_ {
        param($stream)
        $stream | Set-VmsCameraStream -Settings @{ FPS = 0.3 }
    }
}
$jobs | Receive-Job -Wait -AutoremoveJob
```

![image](https://github.com/user-attachments/assets/84c91ffe-8736-4e8b-9598-16a8b1dd0210)

**Comment by joshooaj** [comment]
This seems not to deadlock, but it's not faster on my small test setup with 48 total streams available on a handful of cameras. One of the drawbacks is the 1-second import time for the module since each runspace starts from scratch, even if it's running as a thread in-process.

```powershell
Get-VmsCamera | % {
    Start-ThreadJob -ArgumentList $_ {
        param($cam)
        ipmo milestonepstools
        $cam | Get-VmsCameraStream | Set-VmsCameraStream -Settings @{ FPS = '0.21' }
    }
} | Receive-Job -Wait -AutoRemoveJob
```

**Comment by Silex** [comment]
Well, I thought you needed multiple processes (not threads) as MilestonePSTools is not threadsafe/rentrant (#45).

Anyway you're probably right that the server will likely sequentialize requests anyway so speed increase will be minimal.

On a side note a found a weird typo for "Set-AdaptiveStreaming" on the website:

![image](https://github.com/user-attachments/assets/2f269c13-4ddd-4f7c-a9e2-b7b561203282)

It says the file is named "Group-CamerasByModel.ps1" :-)

**Comment by joshooaj** [comment]
Typo fixed, thanks! And yeah you don't necessarily want to use `Connect-Vms` or `Connect-ManagementServer` in multiple runspaces in the same process, but technically you can use runspaces and do some work in parallel. Once you import the module in another runspace, that runspace is already "connected" because commands will reuse the singleton `[MilestonePSTools.Connection.MilestoneConnection]::Instance`.

The `Get-VmsCameraReport` command is an example of a command heavily using runspaces, though I'm not necessarily proud of the implementation. There's still limited value in my experience though when most of the commands are hitting the management server rather than branching out to query the recording server `RecorderStatusService2` API for example.
