### ISSUE TITLE
Updating Hardware? 

### ISSUE THREAD

**Issue by jdennis319** [MilestoneSystemsInc/PowerShellSamples#158]
Hello,

I am looking for a way to perform mass hardware updates after installing new firmware. Is there a PowerShell that I could run to update the device hardware after a firmware upgrade? 

Thank you, 
Jeremy

**Comment by Tarterman** [comment]
You could run the following which will do a hardware replacement without modifying the driver. It would be equivalent to right-clicking on the hardware in the Management Client and choosing "Replace Hardware" and then just clicking Next through the wizard.

```
Get-VmsHardware | Where-Object Enabled | Set-VmsHardwareDriver -PassThru -Confirm:$false
```
Depending on how many cameras you have, it could take a while.

If you want to try it on a few individual cameras first, just to make sure it is operating properly, you could do this:

```
$hardware = Get-VmsHardware | Where-Object Enabled | Out-GridView -OutputMode Single -Title "Select a hardware device"
$hardware | Set-VmsHardwareDriver -PassThru -Confirm:$false
```
This will prompt for a hardware device selection, and then performs a hardware replacement without modifying the driver. If the resulting hardware change would result in a different number of camera channels connected to the hardware, the replace will fail since "AllowDeletingDisabledDevices" was not specified.  Since `-Confirm:$false` is present, no confirmation will be required before continuing.

**Comment by jdennis319** [comment]
Thank you, that works!
