### ISSUE TITLE
Import-VmsHardware

### ISSUE THREAD

**Issue by greerjl** [MilestoneSystemsInc/PowerShellSamples#36]
Hello,

I've gone through quite a lot of milestone resources, but cannot find a way around an issue I'm having. I'm trying to import a list of about 70 cameras via csv. I've looked at the example section of this repo and when I tried to replicate using the Import-Hardware command that is used I found that it is deprecated. I'm now trying to use Import-VmsHardware. My csv doesn't have username or password stored for security reasons, but the 'UseDefaultCredentials' flag doesn't seem to work. I'd rather not enter my creds 70 different times. Wondering if there is a known workaround for this. I'll attach a screenshot of the error below:

<img width="1028" alt="Screen Shot 2021-11-22 at 2 30 23 PM" src="https://user-images.githubusercontent.com/17304073/142944737-8e5872ed-0dfd-4c12-88b9-6459d4605869.png">

I'll also include a snapshot showing what the two variables are in case that's helpful.
<img width="1057" alt="Screen Shot 2021-11-22 at 2 34 10 PM" src="https://user-images.githubusercontent.com/17304073/142945128-e95a0f26-8993-48f4-87da-b0a5f09a1ff8.png">

Fwiw, I have been able to connect to management server and use other pstools commands. And I did read this in documentation for the command "You can provide zero, or up to 3 credentials to try for each camera. If you do not specify any credentials, UseDefaultCredentials defaults to True, even if the parameter is not present." on this page https://www.milestonepstools.com/functions/import-vmshardware/

**Comment by jhendricks123** [comment]
Hi Jayme,

It looks like you're doing things right and import-vmsHardware is not parsing that column correctly.

I was out for the better part of Monday and Tuesday which left no time to dig into this Yesterday, but I'll take a look on Monday.

Meanwhile, if your cameras have default credentials (root/pass or admin/admin or something) then I'd say there's probably no additional security risk to putting those values in the CSV - just to get through the roadblock of importing.

What do you think is the best solution for this cmdlet for when the cameras all have the same credentials, but they're not default and you don't want them in plain text in the csv?

What about if the cameras all have different passwords and we don't want them in the CSV?

I think the first scenario is really easy to solve for but the second one is tricky.

Thanks for the detailed issue with screenshots btw!

/Josh

**Comment by jhendricks123** [comment]
Can you open up MilestonePSTools.psm1 and change line 2409 assuming you're running version 21.2.2?

**Old line 2409 inside `Import-VmsHardware`**
```powershell
UseDefaultCredentials = if ($credentials.Count -eq 0) { 'True' } else { $row.UseDefaultCredentials -eq 'True' }
```


**New line 2409 inside `Import-VmsHardware`**
```powershell
UseDefaultCredentials = if ($credentials.Count -eq 0) { $true } else { $row.UseDefaultCredentials -eq 'True' }
```

Looks like I had accidentally passed `true` as a string instead of a boolean when passing these parameters on to Start-VmsHardwareScan.

You'll probably need to close and reopen your PowerShell terminal if you had MilestonePSTools imported while editing the file.

The MilestonePSTools.psm1 file is usually found in one of these two paths if you installed into the standard $env:PSModulePath locations:

`C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\21.2.2\MilestonePSTools.psm1`
`C:\Users\<user>\Documents\WindowsPowerShell\Modules\MilestonePSTools\21.2.2\MilestonePSTools.psm1`

It looks like another change to that function is in order as well. While testing using device types that normally require you to explicitly specify a driver instead of using the "automatic" option in the add hardware wizard in Management Client, they don't get added. I think it's because the first step of the function is to pass these through the Start-VmsHardwareScan function which might not work with univeral drivers or other device types that don't normally work with "automatic" discovery.

**Comment by greerjl** [comment]
The new line actually has to be:

`UseDefaultCredentials = if ($credentials.Count -eq 0) { $true } else { $row.UseDefaultCredentials -eq $true }`

The second true also has to be a boolean.
