### ISSUE TITLE
Identical hardware doesn't import to 2nd parallel recording server

### ISSUE THREAD

**Issue by ScottK-888** [MilestoneSystemsInc/PowerShellSamples#37]
Hi,

I'm trying to add the same hardware to 2 recording servers for resilience. eg:
R01 and R01

I execute the following command

**Get-RecordingServer -Name R01 | Import-VmsHardware -Path c:\temp\hardware.csv**

and the hardware imports perfectly to R01 however when i try to add the same hardware CSV to R02 eg:

**Get-RecordingServer -Name R02 | Import-VmsHardware -Path c:\temp\hardware.csv**

It doesn't add the hardware. I does allow me to add the cameras via the usual manual task. I've tried using IP addresses instead of hostnames. I've also tried stopping the recording service one R01 and executing to the cmd again but still no luck.

 I'm hoping that i've missed something. Any help would be appreciated. Thanks

**Comment by joshooaj** [comment]
I'm looking into this now and can confirm that there seem to be more than one case where the import fails unexpectedly. In my simple test case I'm using the Universal 1 Camera Driver and this is one of the drivers that doesn't work with "Autodetect", it can't be discovered using the [MIP SDK HardwareScan](https://doc.developer.milestonesys.com/html/index.html?base=miphelp/class_video_o_s_1_1_platform_1_1_configuration_items_1_1_hardware_scan_server_task.html&tree=tree_search.html?search=hardwarescan) method.

I'm not sure why it's not working in your case since it works on the first Recording Server. At first I thought maybe the "ExistsGlobally" property returned by Start-VmsHardwareScan was causing the add to fail, but it looks like when I pass the scan results to Add-VmsHardware, I'm already using the `-Force` switch to ignore the fact that the device might exist globally.

When you have the camera added to the first recorder, could you try running Start-VmsHardwareScan against the second recording server with the same camera address, driver # and credentials and see what the results look like? Does it look like this?

```text
HardwareAddress UserName MacAddress Validated ExistsLocally ExistsGlobally RecordingServer
--------------- -------- ---------- --------- ------------- -------------- ---------------
                                    False     False         False          EC2AMAZ-EF5APC5(1)
```

**Comment by ScottK-888** [comment]
Hi Josh,

When i run the following cmd with the camera IP address................

Get-RecordingServer | Start-VmsHardwareScan -Address 10.141.107.52 -DriverNumber 711 -Credential (get-credential)

It produces the following output...........

http://10.141.107.52/ root     ACCC8E308DA4 True      True          True           HZLNTDMSTONER01
http://10.141.107.52/ root     ACCC8E308DA4 True      True          True           HZLNTDMSTONER02

...which suggests to me like its already been added.

**Comment by joshooaj** [comment]
Sorry for the delay! After finally looking at this more closely, it looks like the MIP SDK incorrectly says "MacAddressExistsLocal" so the logic in Add-VmsCamera refuses to try to add the camera.

I've reported this to the SDK team to confirm and fix it. I also want to look into a better option for importing hardware - if the driver number is already known, there's not really a compelling reason to do a hardware scan, so I'm thinking we need to refactor so that we doing use Start-VmsHardwareScan at all when not needed.
