### ISSUE TITLE
Set-CameraSetting StreamNumber does not match Get-CameraSetting

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#38]
Hello,

This happens with `MilestonePSTools  1.0.90` so maybe it was already fixed. I have a camera with 3 properties: one JPEG and two H264. For some reasons this one records as JPEG.

``` powershell
PS C:\> $camera | Get-Stream -All

StreamReferenceIdValues : {[JPEG - streamed, 87D3D9D2-20B5-4560-8AEA-0D757135A4A0], [H.264 - streamed, 08E4E906-6816-4913-BF6C-D53E671009C5], [H.264 2 - streamed, 
                          11C412D4-D111-4340-A0FD-5F631A6C9EFD]}
StreamReferenceId       : 87D3D9D2-20B5-4560-8AEA-0D757135A4A0
LiveDefault             : True
LiveModeValues          : {[Always, Always], [Never, Never], [WhenNeeded, WhenNeeded]}
LiveMode                : Always
Record                  : True
ServerId                : VideoOS.Platform.ServerId
Name                    : JPEG - streamed
DisplayName             : JPEG - streamed
Path                    : Stream[c0bdfce6-fbbc-4971-8c30-bcd403b7fcce]
ParentPath              : Camera[c0bdfce6-fbbc-4971-8c30-bcd403b7fcce]/StreamFolder
ItemCategory            : ChildItem
Description             : 
ParentItemPath          : Camera[c0bdfce6-fbbc-4971-8c30-bcd403b7fcce]
```

Here `87D3D9D2-20B5-4560-8AEA-0D757135A4A0` is `JPEG - streamed`.

We see that StreamNumber 0 is JPEG and 1/2 is H264:

``` powershell
PS C:\> $camera | Get-CameraSetting -Stream -StreamNumber 0

FPS Resolution Quality
--- ---------- -------
25  640x480    7      

PS C:\> $camera | Get-CameraSetting -Stream -StreamNumber 1


MaxBitrate          : 2048
Resolution          : 640x480
Quality             : Fine
StreamingMode       : RTP_UDP
MpegControlPriority : ConstantBitrate
FPS                 : 30
MaxGOPMode          : default
MaxGOPSize          : 30

PS C:\> $camera | Get-CameraSetting -Stream -StreamNumber 2

MaxBitrate          : 1536
Resolution          : 640x480
Quality             : Normal
StreamingMode       : RTP_UDP
MpegControlPriority : ConstantBitrate
FPS                 : 30
MaxGOPMode          : default
MaxGOPSize          : 30

PS C:\> $camera | Get-CameraSetting -Stream -StreamNumber 0 -Name FPS -ValueTypeInfo

Setting Property Value  
------- -------- -----  
FPS     MinValue 0.00028
FPS     MaxValue 30.0   

PS C:\> $camera | Get-CameraSetting -Stream -StreamNumber 1 -Name FPS -ValueTypeInfo

Setting Property Value
------- -------- -----
FPS     30       30   
FPS     20       20   
FPS     15       15   
FPS     12       12   
FPS     10       10   
FPS     7.5      7.5  
FPS     5        5    
FPS     3        3    
FPS     1        1    

PS C:\> $camera | Get-CameraSetting -Stream -StreamNumber 2 -Name FPS -ValueTypeInfo

Setting Property Value
------- -------- -----
FPS     30       30   
FPS     20       20   
FPS     15       15   
FPS     12       12   
FPS     10       10   
FPS     7.5      7.5  
FPS     5        5    
FPS     3        3    
FPS     1        1    
```

But, when we try to set StreamNumber 0 we see that it tries to set the h264 stream:

``` powershell
PS C:\> $camera | Set-CameraSetting -Stream -StreamNumber 0 -Name FPS -Value 20
Set-CameraSetting : Exception of type 'VideoOS.Platform.Proxy.ConfigApi.ValidateResultException' was thrown.
At line:1 char:11
+ $camera | Set-CameraSetting -Stream -StreamNumber 0 -Name FPS -Value  ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Settings:DeviceDriverSettings) [Set-CameraSetting], ValidateResultException
    + FullyQualifiedErrorId : stream:0.0.0/Resolution/2b25c3c5-35ba-4ec1-a748-f225732161ed: Resolution is out of range,MilestonePSTools.DeviceCommands.SetCameraSetting
```

It looks like that for `Get-CameraSetting`, streamnumber is `JPEG/h264/h264`, but for `Set-CameraSetting`, it is `h264/h264/JPEG` (like it is in the GUI, JPEG is the last one not the first one).

I'm not sure if you are supposed to fix Get-CameraSetting or Set-CameraSetting.

Also maybe you'd provide a function to compute the stream number we are interested in, at the moment this is what I have:

``` powershell
function GetRecordStreamNumber($camera) {
  $streamNumber = 0
  foreach ($stream in $camera | Get-Stream -All)
  {
    if ($stream.Record -eq $true) {
      break
    }
    $streamNumber++
  }
  $streamNumber
}
```

But I think something based on `StreamReferenceId` would be better.

**Comment by Silex** [comment]
Okay, same problem with latest version 😢 

It really looks like `Set-CameraSetting` follows the GUI and `Get-CameraSetting` follows another logic where the "Record stream" is first.

**Comment by joshooaj** [comment]
Oh, yeah this is a fun one. You notice how the exception error is not only referencing a different stream than the one you're configuring, but it also references an invalid resolution value when you're only changing the FPS?

I believe this is because of a bug in the device pack driver where certain default stream setting values communicated to the management server and stored in SQL don't actually meet the validation rules.

So the server-side of the configuration api proudly sends you all the settings it has for the camera - the general settings and all the stream settings. Then you modify just one value for one of the streams, and the whole collection gets sent back, including the unchanged values for settings in streams you did not modify. Then the whole collection gets validated by the config api and that one setting that was always invalid to begin with, and at no fault to you, means your configuration change gets rejected.

This bug is being at least partially mitigated in 2022 R1 by checking for this situation before sending out the requested config api objects, and swapping invalid values out with an appropriate value instead.

If this is the issue you're having, I think you'll find that at least some of your resolution setting values are set to the display name of the value instead of the actual value it's expected to be.

For example, If your resolution options in Management Client look like "1080p" and "720p", the internal values for those resolution settings might be 1920x1080 and 1280x720.

You might poke at your resolution values with Get-CameraSetting and compare the value with the options returned by the value type info switch and see if you can spot the issue. And either way, try toggling your resolution settings in management client and then retry your fps setting change.

If that works, you can probably update/reset your resolutions first and then change the FPS and whatever other settings you need to change.

Let me know how it goes!

**Comment by Silex** [comment]
Good catch! The funny thing is that *there is no resolution* 😄 

![image](https://user-images.githubusercontent.com/16015/147211643-35a240e2-11a5-4a14-82c7-bf65b53bf143.png)

But `Get-CameraSetting` still returns a resolution of `640x480` for all 3 channels.

So my guess is that this bug in unsolvable because I cannot use the Management Client to set the "right" values.

I could try to set resolution to `$null` but I'm afraid to break something.

**Comment by Silex** [comment]
Beside the obvious question of how to fix this issue I have the following questions:

1. Why can I change values in the Mangement Client and that does not trigger this bug? Is the management client not really using the MIP SDK? Or is MilestonePSTools not using the MIPSDK?
2. With the MIPSDK I use `StreamReferenceId` then use that to find the appropriate DeviceSetting to change (see code below). With MilestonePSTools I only have `-StreamNumber` to play with and to find out which one to use based on some of your examples I'm supposed to loop using `Get-Stream -All` (see code in the other post above). How am I supposed to do with MilestonePSTools? What confuses me in this example is that for this Panasonic camera StreamNumber 0 returns the "JPEG - streamed" channel but in the ManagementClient we see that it's the 3rd one. It's like is MilestonePSTools reordered the channels so StreamNumber 0 is always the first one from the streams tab (the "recording" one).


``` c#
        private StreamChildItem GetCameraStreamRaw()
        {
            var su = Camera.StreamFolder.Streams.First().StreamUsageChildItems.First();
            var realStreamName = su.StreamReferenceIdValues.Where(p => p.Value == su.StreamReferenceId).First().Key;
            
            foreach (var deviceSetting in Camera.DeviceDriverSettingsFolder.DeviceDriverSettings)
            {
                var tmp = deviceSetting.StreamChildItems.Where(c => c.DisplayName == realStreamName).FirstOrDefault();
                if (tmp != null)
                    return tmp;
            }

            return null;
        }
```

**Comment by joshooaj** [comment]
I'm surprised to hear there are resolution settings that are visible with Configuration API and not in Management Client. If the fields are not read-only, you could change them from powershell even if you don't see them in Management Client so that's worth a try.

To answer your second question, I think there's some room to write better cmdlets than the existing Get/Set stream and Get/Set camera setting as they do not give you a good way to find the right stream setting to change from the "stream usage value name/id".

I wrote them when I had a weaker understanding of the settings hierarchy and to be honest I still struggle to communicate the concept of "stream settings" and "stream usage settings". I'd love to rethink new cmdlets for some of this and would take any and all suggestions under advisement :)

To at least point you in the right direction, you can get a reference to the camera, dig into the driver settings folder, then driver settings, then look at the child items attached to that driver settings object. One will usually have the display name "General" and then the others will usually be "Stream 1" and "Stream 2" - matching the names of the stream usage options you see from the Get-Stream request. You would then pick the stream that has the display name matching the one you're after. Might be a way to do it by ID as well.

If you have some time after the new year, maybe we can have a call about it? I'd love to chat about it with someone who has been bitten by the stream settings cmdlets and behavior, and if possible, maybe do a remote session?

**Comment by Silex** [comment]
> I'm surprised to hear there are resolution settings that are visible with Configuration API and not in Management Client. If the fields are not read-only, you could change them from powershell even if you don't see them in Management Client so that's worth a try.

I'll try, but it's surprising the current value of `640x480` would not be valid. I'll try to enumerate the value with `-ValueTypeInfo`.

Also, maybe it's just this specific camera model that triggers some bug.

> To answer your second question, I think there's some room to write better cmdlets than the existing Get/Set stream and Get/Set camera setting as they do not give you a good way to find the right stream setting to change from the "stream usage value name/id".
> 
> I wrote them when I had a weaker understanding of the settings hierarchy and to be honest I still struggle to communicate the concept of "stream settings" and "stream usage settings". I'd love to rethink new cmdlets for some of this and would take any and all suggestions under advisement :)

Yeah, even with the MIPSDK it's not very clear, e.g I'm still not sure if `GetCameraStreamRaw` in my code above is the right way to go.

> To at least point you in the right direction, you can get a reference to the camera, dig into the driver settings folder, then driver settings, then look at the child items attached to that driver settings object. One will usually have the display name "General" and then the others will usually be "Stream 1" and "Stream 2" - matching the names of the stream usage options you see from the Get-Stream request. You would then pick the stream that has the display name matching the one you're after. Might be a way to do it by ID as well.

I think that's what I do... I find the StreamUsage that is recording, use it's value `StreamReferenceId` to get the stream name, then use that name to get the correct DeviceDriverSettings to modify.

If you ask me the MIPSDK should make this much more simple, relying on a string comparison to modify configuration looks fragile to me.

E.g the StreamUsage should reference the DeviceDriverSetting... but then saving it is tricky as you need the Camera object. Oh well.

> If you have some time after the new year, maybe we can have a call about it? I'd love to chat about it with someone who has been bitten by the stream settings cmdlets and behavior, and if possible, maybe do a remote session?

Sure I'd love to, maybe something where we can share screens.

Regards,
Philippe

**Comment by joshooaj** [comment]
> Sure I'd love to, maybe something where we can share screens.

Great, I sent you an email! I agree that using a string to match a "stream usage child item" with a "stream child item" feels like a week correlation and I'd be a lot more confident if the "StreamReferenceId" GUID associated with the "stream usage child item" could be found on the "stream child item" where the associated stream settings are found. So far though it seems like the best way to marry the two. This is what I'm doing in Get-VmsCameraReport to get the configured resolution/fps/codec for the default live stream and the recorded stream.

```powershell
$cam.DeviceDriverSettingsFolder.DeviceDriverSettings[0].StreamChildItems | Where-Object DisplayName -eq $liveStreamName
```

Or better yet, sticking with the config api design of using "ItemType[guid]" strings as "Paths" to configuration items, if the stream reference id was a path, then it would be trivial to ask specifically for that item. But the way the MIP SDK represents stream settings is as child items of the "DeviceDriverSettings" and child items don't get their own paths or ID's.

The configuration api is being reimplemented as a REST API more or less as-is so I'm not sure we'll see a more concrete method of jumping between stream usages and stream settings, but the StreamReferenceIdValues _should_ match the display names of the stream child items.

We can definitely come up with a PowerShell cmdlet to simplify this, I just don't want to make any new additions or changes to the module without a lot more thought about how we can pave over some of the MIP SDK complexity in a way that is easily understood and maintainable long term. A lot of the early cmdlets need to be deprecated for higher quality, alternatives in my opinion - I just don't know yet what those alternatives would look like. Preferably they would not return pscustomobject's or hashtables and favor either raw MIP SDK objects or custom types.

**Comment by Silex** [comment]
Just an update about the resolution:

``` powershell
PS C:\Users\ext-adm-pva> $camera | Get-CameraSetting -Stream -StreamNumber 0 -Name Resolution -ValueTypeInfo
PS C:\Users\ext-adm-pva> $camera | Get-CameraSetting -Stream -StreamNumber 0 -Name Resolution

Resolution
----------
640x480

PS C:\Users\ext-adm-pva> $camera | Set-CameraSetting -Stream -StreamNumber 0 -Name Resolution -Value 640x480
Set-CameraSetting : Exception of type 'VideoOS.Platform.Proxy.ConfigApi.ValidateResultException' was thrown.
At line:1 char:11
+ $camera | Set-CameraSetting -Stream -StreamNumber 0 -Name Resolution  ...
+           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (Settings:DeviceDriverSettings) [Set-CameraSetting], ValidateResultExceptio
   n
    + FullyQualifiedErrorId : stream:0.0.0/Resolution/2b25c3c5-35ba-4ec1-a748-f225732161ed: Resolution is out of range
   ,MilestonePSTools.DeviceCommands.SetCameraSetting

PS C:\Users\ext-adm-pva> $camera | Set-CameraSetting -Stream -StreamNumber 0 -Name Resolution -Value $null
Set-CameraSetting : Cannot bind argument to parameter 'Value' because it is null.
At line:1 char:77
+ ... t-CameraSetting -Stream -StreamNumber 0 -Name Resolution -Value $null
+                                                                     ~~~~~
    + CategoryInfo          : InvalidData: (:) [Set-CameraSetting], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,MilestonePSTools.DeviceCommands.SetCamera
   Setting
```

Seems like there's no ValueTypeInfo for Resolution yet I can't set a valid value or $null.

**Comment by joshooaj** [comment]
Unfortunately I don't have immediate access to a WV-NW502, I'll have to poke around some of our camera labs to see if there's one laying around.

I greatly appreciate you taking the time to chat with me the other week. I haven’t gotten to the stream settings yet, but I’m working on an update to `Get-Camera` and a new `Set-VmsCamera` cmdlet. If you’re interested in checking them out, you can download a prerelease of 21.2.3 from https://download.milestonesys.com/jh/MilestonePSTools_21.2.3.zip

The new cmdlets are `Get-VmsCamera` and `Set-VmsCamera`.

The great thing about Get-VmsCamera is that it doesn’t require you to give it a hardware object – you can perform a search by name alone if you want. That is enabled by the Configuration API “QueryItems” method introduced in 2020 R2. I haven’t tested yet to be sure it fails with a nice error but I put an assert in there on the VMS version so that if you try to use it without running version 2020 R2 or later on the server, you should get an error explaining why it won’t work. Getting cameras by hardware or by ID still work on 2020 R1 or earlier though.

And `Set-VmsCamera` makes it easier to modify all the properties directly attached to the camera object. Name, description, GPS, orientation, prebuffer and recording. It supports WhatIf and provides verbose output showing exactly which parameters were modified for each camera.

From here I will probably add Get/Set-VmsCameraStream cmdlets like we discussed and try to wrap ALL stream/streamusage information into those cmdlets so things are a bit easier on the user. Something like `Get-VmsCameraStream -DefaultLive” or “Get-VmsCameraStream -Recorded` to access those one/two “special streams” that are in actively used. And then maybe an `Get-VmsCameraStream -All` option to get them all, as well as a `-Name` selector.

From there I think something like `Set-VmsCameraStream -Recorded -DefaultLive -LiveMode WhenNeeded -Settings @{ FPS = 15; Codec = ‘h264’ }` could make sense, where you provide the new settings in a dictionary/hashtable? The `Set-CameraSetting` cmdlet is a bit easier to use for changing stream settings, except each setting change is done in a different API call, so if you change three properties on 100 cameras, it’s 300 api calls. And since every camera driver has different stream setting keys, I can’t reliably even put the popular FPS/Codec/Resolution ones as parameters on the cmdlet because not every camera has those.

As a rough idea I’m thinking `Get-VmsCameraStream` returns something like…

![image](https://user-images.githubusercontent.com/7669972/149240457-3363df2e-828d-459a-82f5-9a4d4aca1475.png)

From there, you could do `$example | Set-VmsCameraStream -DisplayName ‘Low-resolution’ -DefaultLive -Settings { Resolution = ‘640x480’ }`. Then the live stream gets set to true and we set it to false on the currently-active default live stream. Same if `-Recorded` is used - set it to true on the specified stream and set to to false on any others before pushing the changes to the management server.

**Comment by Silex** [comment]
It sounds great! I like the HashTable approach.

It raises a few questions tho:
- To delete a stream from the streams tab you set `Recorded` and `DefaultLive` to false?
- In the MC, you can add a stream that has `Recorded` and `DefaultLive` unticked. Not that it's usefull, but you can. Would that be impossible with Set-VmsCameraStream?

**Comment by joshooaj** [comment]
Good questions! I made some more progress on the concept today which addresses those.

One of the other things I want to think about is how the user should discover what the valid values are for settings. The `Get-CameraSetting` cmdlet has a `-ValueTypeInfos` switch which will dump information about the properties and their valid ranges/values. Not sure if `Get-VmsCameraStream` should have something similar yet. Maybe each stream object returned to the caller should include a `SettingsValueTypeInfos` or some other better named property so there's no other extra call to make to get that information?

## Listing streams

Enabled is `$true` if there is a "Stream Usage" pointing to that stream name

```powershell
$streams = $camera | Get-VmsCameraStream
$streams | Get-VmsCameraStream | Format-Table
<#
Name           DisplayName     Enabled LiveDefault LiveMode   Recorded Settings
----           -----------     ------- ----------- --------   -------- --------
Video stream 1 Live Stream        True       False Always         True {ControlMode, RetentionTime, StreamingMode, FPS...}
Video stream 2 Recorded Stream    True       False WhenNeeded    False {ControlMode, RetentionTime, StreamingMode, FPS...}
Video stream 3                   False       False               False {ControlMode, RetentionTime, StreamingMode, FPS...}
Video stream 4                   False       False               False {ControlMode, RetentionTime, StreamingMode, FPS...}
Video stream 5 Video stream 5     True        True WhenNeeded    False {ControlMode, RetentionTime, StreamingMode, FPS...}
Video stream 6                   False       False               False {ControlMode, RetentionTime, StreamingMode, FPS...}
Video stream 7                   False       False               False {ControlMode, RetentionTime, StreamingMode, FPS...}
Video stream 8                   False       False               False {ControlMode, RetentionTime, StreamingMode, FPS...}
#>
```

## Removing streams

You cannot remove a stream unless you first move the LiveDefault and Recorded properties to another stream.

```powershell
$streams[0] | Set-VmsCameraStream -Disable -Verbose
<#
VERBOSE: Performing the operation "Disabling stream 'Video stream 1'" on target "Cam Lab Camera".
#>
```

## Updating properties

```powershell
$streams[0] | Set-VmsCameraStream -LiveDefault -DisplayName 'Live Stream' -Settings @{ FPS = 11 } -Verbose

<#
VERBOSE: Performing the operation "Adding a new stream usage" on target "Cam Lab Camera".
VERBOSE: Performing the operation "Setting DisplayName on Video stream 1" on target "Cam Lab Camera".
VERBOSE: Performing the operation "Disabling LiveDefault on Recorded Stream" on target "Cam Lab Camera".
VERBOSE: Performing the operation "Enabling LiveDefault on Live Stream" on target "Cam Lab Camera".
VERBOSE: Performing the operation "Saving StreamUsages" on target "Cam Lab Camera".
VERBOSE: Performing the operation "Changing FPS from 1 to 11" on target "Video stream 1 on Cam Lab Camera".
VERBOSE: Performing the operation "Save changes" on target "Video stream 1 on Cam Lab Camera".
#>
```

**Comment by joshooaj** [comment]
I have an updated preview of MilestonePSTools v21.2.3 - ****[Download](https://download.milestonesys.com/jh/MilestonePSTools_21.2.3.zip)****

It includes four new cmdlets:

- `Get-VmsCamera`
- `Set-VmsCamera`
- `Get-VmsCameraStream`
- `Set-VmsCameraStream`

There are detailed examples in the Get-Help docs for each, and _hopefully_ I've covered nearly all the bases. Based on one of the original issues in this thread, I think you were trying to get/change the settings associated with a specific stream like the "LiveDefault" stream. If you wanted to change the FPS on that specific stream, and you know it has a stream setting named "FPS", then you can do it in one line now...

```powershell
$camera | Get-VmsCameraStream -LiveDefault | Set-VmsCameraStream -Settings @{ FPS = 15 } -Verbose
```

And if you wanted to see what the valid values are for "Codec" you can do...

```powershell
$stream = $camera | Get-VmsCameraStream -LiveDefault
$stream.ValueTypeInfo.Codec

<# OUTPUT
TranslationId                        Name  Value
-------------                        ----  -----
76c84c36-d7f8-47fe-9cd2-8ffb1ef85760 MJPEG jpeg
cf1e23d9-701a-4407-bdfd-997f2d77483f H.264 h264
d58b0c16-159b-4fa8-b62a-79b244591b40 H.265 h265
#>
```

If you get a chance to test this out, let me know how it works for you. Hopefully it is a lot more intuitive!

**Comment by Silex** [comment]
The `-ValueTypeInfo` switch in the current version is very usefull. For example when setting FPS given some hardware accept any integer between 1 and 60 and others only use a fixed set, I use that to query before trying to set the desired value (if it's a range then I just cap my fps to the range, if it's a fixed set I find the closest value to).

Your examples looks nice, I'll try to give it a test but I'm pretty busy this week, I'll keep you updated.

**Comment by joshooaj** [comment]
No worries, if you get a chance this week I'd love to get feedback before publishing.

The Get-Help docs for the upcoming commands are available online now - hopefully the examples are better than they have been in the past 😅

https://www.milestonepstools.com/functions/get-vmscamerastream/

**Comment by Silex** [comment]
I did a quick test, it looks nice. I found a little bug:

```
PS C:\Users\Philippe Vaucher> $streams[2] | Set-VmsCameraStream -Verbose -Settings @{ FPS=14; Resolution='800x600'}
VERBOSE: Performing the operation "Changing Resolution from 1920x1080 to 800x600" on target "Video stream 3 on AXIS
Q6125-LE PTZ Dome Network Camera (10.13.37.25) - Camera 1".
VERBOSE: Performing the operation "Save changes" on target "Video stream 3 on AXIS Q6125-LE PTZ Dome Network Camera
(10.13.37.25) - Camera 1".
Set-VmsCameraStream : Validation error: Failed to set stream:0.0.2/Resolution/2b25c3c5-35ba-4ec1-a748-f225732161ed to
"". Reason: Resolution is out of range.
At line:1 char:15
+ ... treams[2] | Set-VmsCameraStream -Verbose -Settings @{ FPS=14; Resolut ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], ValidateResultException
    + FullyQualifiedErrorId : VideoOS.Platform.Proxy.ConfigApi.ValidateResultException,Set-VmsCameraStream
PS C:\Users\Philippe Vaucher> $streams[2] | Set-VmsCameraStream -Verbose -Settings @{ FPS=14; Resolution='1920x1080'}
VERBOSE: Performing the operation "Changing Resolution from 800x600 to 1920x1080" on target "Video stream 3 on AXIS
Q6125-LE PTZ Dome Network Camera (10.13.37.25) - Camera 1".
VERBOSE: Performing the operation "Save changes" on target "Video stream 3 on AXIS Q6125-LE PTZ Dome Network Camera
(10.13.37.25) - Camera 1".
```

At the end it says that it changes from 800x600 to 1920x1080 despire 800x600 being an error from the latest attempt to set an invalid resolution. Looks like it sets some internal then tries to save the real value, it'd do it the other way around.

**Comment by joshooaj** [comment]
Thanks! So the way the MIP SDK / Configuration API works is you get a Camera "model" object locally, and when you make changes to it, those changes are just to the local model. When you call `.Save()`, the object serializes itself and sends it to the Configuration API SOAP interface on the Management Server where it gets validated. If the change wasn't valid, the modification to the local copy of the camera object aren't rolled back.

To deal with that, I'm now calling `ClearChildrenCache()` when a validation error occurs.

I also had not anticipated the big long setting key name coming back in the validation error. The SDK actually uses "stream:0.0.2/Resolution/2b25c3c5-35ba-4ec1-a748-f225732161ed" as the key for the Resolution setting, but I'm pulling the middle part out and displaying that in PowerShell because nobody wants to see the long version. But I wasn't pulling that user-friendly key name out of the validation error to plug into the custom validation error message. So that should now be handled better when these changes are released.

**Comment by joshooaj** [comment]
Version 21.2.3 is now published on the gallery and the docs for the new cmdlets can be found on www.MilestonePSTools.com.

They are...

- Get-VmsCamera
- Set-VmsCamera
- Get-VmsCameraStream
- Set-VmsCameraStream
- Get-VmsCameraGeneralSetting
- Set-VmsCameraGeneralSetting

**Comment by Silex** [comment]
Nice!

We plan on upgrading to 2021 R2 so I'll maybe be able to test this issue with the new API and check wether the Panasonic camera also fails with it.

**Comment by joshooaj** [comment]
Let us know how it goes! I'm going to close this issue just to tidy things up - feel free to open a new issue if needed!
