### ISSUE TITLE
Get-snapshot (all)

### ISSUE THREAD

**Issue by rudkinp** [MilestoneSystemsInc/PowerShellSamples#40]
Trying to get an occassional report of all active cameras and a snapshot included in the export. Trying to figure out what is the best method for doing this

**Comment by joshooaj** [comment]
Hi @rudkinp,

I finally had a chance to revisit the ImportExcel module and how to work with images. Originally, I proposed a change to the ImportExcel module's `Export-Excel` cmdlet to add handling of `System.Drawing.Image` objects. But supporting and maintaining that is a challenge since there could be a lot of different things people want to do with image placement, alignment, cell sizing, etc. Here's the issue I had open with dfinke: https://github.com/dfinke/ImportExcel/issues/1041

Following his suggestion to use the `Export-Excel` cmdlet with the `-PassThru` switch, here's what I came up with as an alternative for adding images from MilestonePSTools.

The first cmdlet, `Add-ExcelImage`, can be used with the ImportExcel module independently from MilestonePSTools and allows you to put an Image object in a worksheet at specific column/row coordinates with the option to increase the row height or column width to fit the image.

The second cmdlet is an example of how you might *use* the first cmdlet. It uses the new Get-VmsDeviceStatus cmdlet (from MilestonePSTools v21.2.5) to get camera status, and then uses Get-Snapshot to retrieve a full-quality live image. From there, I'm using a couple of MilestonePSTools cmdlets to convert the byte array to an Image, and processing that image down to a smaller size for the spreadsheet.

Hopefully you can use this example and adjust it to your needs so that the spreadsheet has the data you're interested in.

```powershell
#Requires -Module MilestonePSTools, ImportExcel

function Add-ExcelImage {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory, ValueFromPipeline)]
        [System.Drawing.Image]
        $Image,

        [Parameter()]
        [string]
        $Name,

        [Parameter(Mandatory)]
        [OfficeOpenXml.ExcelWorksheet]
        $WorkSheet,

        [Parameter(Mandatory)]
        [ValidateRange(1, [int]::MaxValue)]
        [int]
        $Row,

        [Parameter(Mandatory)]
        [ValidateRange(1, [int]::MaxValue)]
        [int]
        $Column,

        [Parameter()]
        [switch]
        $ResizeCell
    )

    begin {
        $widthRatio = 17 / 120
        $heightRatio = 3 / 4
    }

    process {
        if ([string]::IsNullOrWhiteSpace($Name)) {
            $Name = (New-Guid).ToString()
        }
        $picture = $WorkSheet.Drawings.AddPicture($Name, $Image)
        $picture.SetPosition($Row - 1, 0, $Column - 1, 0)
        $width = $widthRatio * $Image.Width
        $height = $heightRatio * $Image.Height

        if ($ResizeCell) {
            $WorkSheet.Column($Column).Width = [Math]::Max($width, $WorkSheet.Column($Column).Width)
            $WorkSheet.Row($Row).Height = [Math]::Max($height, $WorkSheet.Row($Row).Height)
        }
    }
}

function Export-VmsState {
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)]
        [string]
        $Path,

        [Parameter()]
        [switch]
        $IncludeSnapshots,

        [Parameter()]
        [int]
        $ImageHeight = 300
    )

    process {
        try {
            $deviceStatus = Get-VmsDeviceStatus | Select-Object -First 10
            $pkg = $deviceStatus | Export-Excel -Path $Path -PassThru:($IncludeSnapshots)
            if ($IncludeSnapshots) {
                $imageColumn = ($deviceStatus | Get-Member -MemberType Property).Count + 1
                $worksheet = $pkg.Sheet1
                $worksheet.SetValue(1, $imageColumn, 'Snapshot')
                for ($i = 0; $i -lt $deviceStatus.Count; $i++) {
                    $row = $deviceStatus[$i]
                    $snapshot = Get-Snapshot -CameraId $row.DeviceId -Live -Quality 100
                    if ($snapshot.Content.Length -gt 0) {
                        $image = ConvertFrom-Snapshot -Content $snapshot.Content
                        $resizedImage = $image | Resize-Image -Height $ImageHeight -Quality 100 -OutputFormat JPEG -DisposeSource
                        # Row is $i + 2 because excel rows are numbered from 1, and the first row of the spreadsheet has headers.
                        Add-ExcelImage -Image $resizedImage -WorkSheet $worksheet -Row ($i + 2) -Column $imageColumn -ResizeCell -Name $row.DeviceId
                    }
                    
                }
            }
        } finally {
            if ($pkg) {
                $pkg.Save()
                $pkg.Dispose()
            }
        }
    }
}

Export-VmsState -Path ~\Downloads\camera-state.xlsx -IncludeSnapshots
```

**Comment by joshooaj** [comment]
Here's an example of using the Add-ExcelImage cmdlet with the output from Get-VmsCameraReport which has the -IncludeSnapshots switch:

```powershell
$report = Get-VmsCameraReport -IncludeSnapshots -SnapshotHeight 300
$snapshotColumn = ($report | Get-Member -MemberType NoteProperty).Count
$pkg = $report | Select-Object -ExcludeProperty Snapshot | Export-Excel -Path ~\Downloads\Camera-Report.xlsx -PassThru
$sheet = $pkg.Sheet1
for ($i = 0; $i -lt $report.Count; $i++) {
    if ($null -ne $report[$i].Snapshot) {
        Add-ExcelImage -Image $report[$i].Snapshot -Row ($i + 2) -Column $snapshotColumn -ResizeCell -WorkSheet $sheet
    }
}
$pkg.Save()
```

**Comment by joshooaj** [comment]
I'll try to publish a new guide on the docs site before the end of the week. Until then, here is a GitHub gist where I've tried to clean this up and make it really easy to use. The report comes out really nice when formatted as a table. I'll close this issue now as I think/hope this provides a solid recommendation on how to work with images in a report, and it does not depend on a customized version of ImportExcel. Let me know if you have any questions/issues!

https://gist.github.com/joshooaj/153bf539ca0235f006f67dca394241c7
