### ISSUE TITLE
Basic thread safety

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#45]
Hello,

I jumped from `1.0.90` to `21.2.7` (yeah quite the jump :laughing:) and it looks like basic thread safety is gone.

I use https://github.com/nightroman/SplitPipeline to parallelize my scripts (I query the same information over 50+ sites) and basically the first server connects then all the other say:

`Error: Already connected to a Management Server`

Do you plan on supporting basic thread safety or should I switch to process parallelism?

**Comment by joshooaj** [comment]
It sounds like you're including a "Connect-ManagementServer" call _inside_ your scriptblock that is being run in a runspace? If you make your connection _outside_ of that scriptblock then you should be fine - I use runspaces often without any issues.

The issue doesn't have anything to do with thread safety. The issue is that the Connect-ManagementServer command is designed to throw a terminating error if you're already logged in and you try to establish a new management server connection without using the `-Force` switch.

If you were using plain "jobs" instead of runspaces, then those jobs would each run in their own process and you could authenticate to the same (or different) management server from each process. With runspaces, you're sharing state between all runspaces (at least, .NET state - not powershell session state). So you don't need to authenticate in each thread.

Where I can see this causing you problems is if you were trying to multi-thread actions against multiple different management servers simultaneously. While MIP SDK does allow this, MilestonePSTools isn't well equipped to let you do it right now. The reason is that assumptions are made for basically all commands that the "ServerId" is the server you're logged in to at the moment, or in the case of federated architecture, whatever site was selected last with `Select-Site`. So when you use `Get-VmsManagementServer` you will get a ManagementServer object representing whatever site you get when you run `Get-Site`. And `Get-RecordingServer` will return all the recording servers from that site.

To make MilestonePSTools support multithreaded access to multiple sites simultaneously from a single PowerShell session, all the commands would have to take an optional "ServerId" or "Site" property. My instinct is that this would add an uncomfortable amount of complexity and risk, and require updating a large number of commands for a very niche scenario.

**Comment by Silex** [comment]
Well in case it was not clear I run one script, which uses `Split-Pipeline` to connect to 50+ differents servers and that's why I need to `Connect-ManagementServer` inside the scriptblock.

But from what you said I infer that it was merely a coincidence that it was working in `1.0.90` and that I need to use plain jobs (processes).

I always assumed runspaces where just threads but apparently not :sweat_smile:

I come from a C++/Ruby background so some powershell concepts are not entirely clear to me, I assumed `Connect-ManagementServer` was reentrant and thread safe but it's becoming clear it is not :-)

I'll switch to plain jobs or something else. Thanks!

**Comment by joshooaj** [comment]
Yeah I'm surprise it worked at all the way you had hoped before tbh - the concept of having a single site selected at a time has been a part of the module from the beginning if I recall.

Depending on the circumstances, you could also consider setting up a scheduled task on each system and push the results out to something like a bucket/blob or post the results to an azure function/lambda. Otherwise yes the safest way to do it is to run the operations for each site in their own thread.

You're able to multithread requests within the same site without issue. So you might do multiple Get-PlaybackInfo operations in parallel to discover start/end times for the media databases of all cameras.

Runspaces are basically separate threads so you're not wrong. As I understand it they're a separate thread with their own powershell session/context. So you can't share variables between runspaces except through arguments, but since they're running in process, they access the same .NET runtime so you have access to shared singletons or other state that you can get to using class syntax.

**Comment by Silex** [comment]
> Otherwise yes the safest way to do it is to run the operations for each site in their own thread.

In their own *process* right? :wink:
