### ISSUE TITLE
`Get-LicenseDetail` not working with 2020R1 servers anymore

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#46]
Hello,

There's a regression with `Get-LicenseDetail`:

```
PS C:\Users\ext-adm-pva> Get-VmsManagementServer

Name           Version  ComputerName   TimeZone            LastModified        Id
----           -------  ------------   --------            ------------        --
XXXXXXXXX 20.1.0.1 XXXXXXX China Standard Time 29.03.2022 15:51:55 XXXXXXXX-4855-4F84-AEF4-1XXXXXXXX


PS C:\Users\ext-adm-pva> Get-LicenseDetails
Exception calling ".ctor" with "2" argument(s): "The server doesn't support the specified path
Parameter name: path"
At C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\21.2.7\MilestonePSTools.psm1:5516 char:114
+ ... ew($site.FQID.ServerId, "LicenseInformation[$($site.FQID.ObjectId)]")
+                                                   ~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ArgumentMIPException
```

It works if the server is 2021R2 tho.

We are migrating it all to 2021R2 so it's not a big deal but I thought you'd like to know.

**Comment by joshooaj** [comment]
Which version of MilestonePSTools supported `Get-LicenseDetails` against 2020 R1? As far as I can tell, the Configuration API path "/LicenseInformationFolder" was introduced by the server as of version 2020 R2 and it can't work on any version prior to that.

Assuming I'm correct, I'll definitely add a version constraint to the begin block on `Get-LicenseDetails` so that when it's invoked, an assertion will be made that the server version is at least 20.2 and if not, a more informative error message is thrown.

**Comment by Silex** [comment]
Version `1.0.90` did. Well at least it didn't throw an error and returned mostly accurate informations, tho sometimes it missed some keys.

**Comment by joshooaj** [comment]
I'm not sure how that could have worked against 2020 R1 when it's the server that needs to support the Configuration API path and it wasn't introduced until 2020 R2. Are you saying you can 'Import-Module MilestonePSTools -RequiredVersion 1.0.90' and run the command against your 2020 R1 server and it works?

**Comment by Silex** [comment]
Yes, I just tested:

```
PS C:\Users\ext-adm-pva> Import-Module MilestonePSTools -RequiredVersion 1.0.90
PS C:\Users\ext-adm-pva> Connect-ManagementServer SOMESERVER
PS C:\Users\ext-adm-pva> (Get-ManagementServer).Version
20.1.0.1
PS C:\Users\ext-adm-pva> Get-LicenseDetails

State            : Valid
ErrorMessage     : System.Object
ExpirationDate   : 31.12.9999 23:59:59
ActivationDate   : 06.01.2022 14:01:30
SLC              : M01-C01-201-01-XXXXXX
ProductName      : XProtect Corporate 2020 R1
EncryptedSlc     : 23915516115007311822816316221409007521004720003XXXXXXXXXXXXXXXXXXXXX
Customer         : MilestoneLib.LicenseInformationCustomer
Sites            : {XXXXXXXXXXXXXX}
Features         : {Audio, DeviceChannels, DLKQuota, Metadata...}
RecorderLicenses : MilestoneLib.LicenseInformationRecorderLicenses
HardwareLicenses : MilestoneLib.LicenseInformationHardwareLicenses
TotalActivated   : MilestoneLib.LicenseInformationTotalActivated
FeedLicenses     : {Camera, AudioInput, AudioOutput, Metadata...}
ICPFeedLicenses  : {Camera, AudioInput, AudioOutput, Metadata...}
```

**Comment by joshooaj** [comment]
Circling back to this, it looks like the `Get-LicenseDetails` cmdlet was originally written in C# and used ServerProxyService back then. It has since been replaced with a powershell based function using the Configuration API where the license details are found under the `/LicenseInformationFolder` config api path, and that path was introduced in management server version 2020 R2.

I added an `Assert-VmsVersion` to all the license-related cmdlets so that a more useful error is logged:

"Management of Milestone XProtect VMS licensing using MIP SDK was introduced in version 2020 R2 (v20.2). This function is not compatible with your current Management Server version."
