### ISSUE TITLE
How to clear Recording Server cache?

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#57]
Hello,

I have two servers that have identical DBs.

If I connect to each one right after one another, `Get-RecordingServer` returns the same objects:

``` ps1
foreach($server in $servers) {
  try {
    'Connecting to {0}' -f $server
    Connect-ManagementServer -Server $server
    foreach($recorder in Get-RecordingServer) {
      Write-Warning ('Name: {0}' -f $recorder.Name)
    }
  }
  catch {
    Write-Warning ("{0}: {1}`n   {2}" -f $server, $_, $_.ScriptStackTrace)
  }
  finally {
    Disconnect-ManagementServer
  }
}
```

This outputs the correct `Connecting to...` lines but then `Name:` is the same as server 1 even when connected to server 2.

**Comment by joshooaj** [comment]
Weird! Does `Clear-VmsCache` help? I would have expected `Disconnect-ManagementServer` to take care of it for you on it's own. If adding that to your script fixes it, I'll be sure to update the disconnect cmdlet as you definitely shouldn't have to manually clear the cache in that instance.

A while back I made it so that the root "ManagementServer" object is cached, and whenever you `Get-*` one of the VMS objects like recorders, hardware, cameras, etc without specifying an ID, it enumerates through the configuration starting from that cached ManagementServer object. So something like `ManagementServer.RecordingServerFolder.RecordingServers`. And the strongly typed configuration api objects automatically cache their child items when you access them. By taking advantage of that cache, multiple enumerations of the same objects becomes _a lot faster_. But the side effect is that sometimes the cache needs to be cleared, especially when adding/removing objects and expecting to find them in the config after. So in some cmdlets I'm making sure to add a call to `.ClearChildrenCache()` on the parent node closest to the change so that the next enumeration of that folder shows those changes.

**Comment by Silex** [comment]
Ok, `Clear-VmsCache` does not change anything:

``` powershell
foreach($server in $servers) {
  try {
    'Connecting to {0}' -f $server
    Connect-ManagementServer -Server $server
    foreach($recorder in Get-RecordingServer) {
      'Name: {0}' -f $recorder.Name
    }
  }
  catch {
    Write-Warning ("{0}: {1}`n   {2}" -f $server, $_, $_.ScriptStackTrace)
  }
  finally {
    Clear-VmsCache
    Disconnect-ManagementServer
  }
}
```

This outputs:

```
Connecting to SERVER1-MS
Name: SERVER1-R01
Name: SERVER1-R02
Name: SERVER1-R03
Connecting to SERVER2-MS
Name: SERVER1-R01
Name: SERVER1-R02
Name: SERVER1-R03
```

**Comment by Silex** [comment]
I confirm that calling `[VideoOS.Platform.ClientControl]::Instance.Close()` after `Disconnect-ManagementServer` fixes the problem.

**Comment by Silex** [comment]
Actually, wait.

I was testing with `21.2.7`. With `22.0.0` it behaves properly, even without `Clear-VmsCache`.

I'm confused, also with `22.0.0` I randomly get errors when connecting to servers.
