### ISSUE TITLE
Get-User filtering

### ISSUE THREAD

**Issue by OlivierPaget** [MilestoneSystemsInc/PowerShellSamples#6]
Hi Josh
I try to use Get-User, for example to check if a user exists before creating it.
Get-User returns a list of properties including AccountName
Get-User -AccountName "MyAccountName" doesn't work. Just -Username is available.
Get-User -Username "MyAccountName" always return all users.
How can I filter by my user name or account name ? What am I doing wrong ?

Thanks a lot in advance for your answer
Olivier
I'm using milestonepstools.1.0.73

**Comment by jhendricks123** [comment]
Hi Olivier,

Thanks for posting this - I had a look and unless the RoleName parameter was also provided, neither the role or username filters were being used due to the way I am using the ParameterSetName property in PowerShell.

When I publish v1.0.77, it'll include a fix for this so that Get-User -UserName somename works. Until then, you'll need to filter it with a Where-Object or in an if-statement within a foreach. For example...

`Get-User | Where-Object AccountName -like 'somename'`

or

```powershell
foreach ($user in Get-User) {
  if ($user.AccountName -notlike 'somename') {
    continue
  }
  # otherwise do some work
}
```

**Comment by OlivierPaget** [comment]
Hi Josh

Thanks a lot for your great support. This Github portal is awesome.
Let me know if I should continue by mail or on the portal.

It looks like the Get-User is related to Role membership. I guess this is like this in the Milestone database.
If I run a Get-User | Where-object

-        I get 2 answers if the (Domain) user is member of 2 roles

-        I have no answer if the (Basic) user is not member of any role
I think it’s logic for Windows users: a Window user doesn’t exist in Milestone if it is not member of a Role
But that means, we can’t really manage Basic users.
For the same reason, I don’t find a solution to create Basic users. Add-User is not done for that.

Thanks again
Olivier Paget

**Comment by jhendricks123** [comment]
Hi Olivier,

The Get-User cmdlet will enumerate the matching users within a matching role, or all users of all roles. And since a user can be a member of more than one role, the cmdlet can return the same user more than once.

If you want to manage basic users such as to add, delete, or modify the user properties, you can do so through the "BasicUserFolder". Here's some examples of how

```powershell
$basicUserFolder = (Get-ManagementServer).BasicUserFolder

# Get all basic users
$basicUserFolder.BasicUsers

# Add a basic user by passing credentials in plain text
$result = $basicUserFolder.AddBasicUser('name', 'description', 'password')

# Add a basic user by passing securestring for password
# Obviously you should do something different to create the securestring
$password = 'password' | ConvertTo-SecureString -AsPlainText -Force
$result = $basicUserFolder.AddBasicUser('name', 'description', $password)

# Retrieve the new basic user object and add it to the role named 'TestRole'
if ($result.State -eq 'Success') {
    $user = $basicUserFolder.BasicUsers | Where-Object Path -eq $result.Path
    Get-Role -Name 'TestRole' | Add-User -Sid $user.Sid
}
```

**Comment by OlivierPaget** [comment]
The Basic User creation works perfectly fine.
thank you
Olivier

**Comment by jhendricks123** [comment]
Version 1.0.77 was published to PSGallery about two weeks ago and this issue has been solved with that release. Thanks again for reporting this issue!
