### ISSUE TITLE
Motion settings

### ISSUE THREAD

**Issue by jamesangi** [MilestoneSystemsInc/PowerShellSamples#63]
I noticed that MotionThreshold is missing from the camera report.  Would it be possible to add this?  Also, the motion settings don't seem to be exposed outside of the report (ie using the Get-* cmdlets).  Would it be possible to set motion settings at some point?

**Comment by joshooaj** [comment]
Hi @jamesangi, thanks for opening an issue on this!

I've gone ahead and added a MotionThreshold column. I've also updated the MotionManualSensitivity column to take the ManualSensitivity value from Milestone and divide it by 3 since that seems to be how it is represented in the Management Client. For example, in Management Client, if it shows a value of 33, the SDK reports a value of "100". I think we'd rather see the value displayed in the Management Client in this report.

There will be a number of updates in the next pstools release as I work through a backlog of issues and this change will be included in the next push to PSGallery.

In the meantime, while there isn't a cmdlet for getting/setting motion settings yet, here's how you can find them...

```powershell
$camera = Select-Camera
$motionSettings = $camera.MotionDetectionFolder.MotionDetections[0]
$motionSettings
```

And modify them...

```powershell
$camera = Select-Camera
$motionSettings = $camera.MotionDetectionFolder.MotionDetections[0]
$motionSettings.Threshold = 1500
$motionSettings.Save()
```

Cheers,

Josh
