### ISSUE TITLE
Start-Export Error - NoVideoInTimeSpanMIPException

### ISSUE THREAD

**Issue by jdelaughter** [MilestoneSystemsInc/PowerShellSamples#64]
I'm getting an error that there is no video in the selected time period when there definitely is.
VMS Version Tested: `2020 R3 and 2021 R2`
MilestonePSTools Version: `22.1.0`

I'm entering the following:

```
Start-Export -CameraIDs XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX -StartTime '7/11/2022 12:00:00 AM' -EndTime '7/11/2022 12:05:00 AM' -format DB -Path "V:\7-11-2022-Export" -Name "7-11-2022 Export" -Verbose
```

```
Start-Export : No video in selected time period
At line:1 char:1
+ Start-Export -CameraIDs XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX -StartTi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (VideoOS.Platform.Data.DBExporter:DBExporter) [Start-Export], NoVideoInTimeSpanMIPException
    + FullyQualifiedErrorId : VideoOS.Platform.NoVideoInTimeSpanMIPException: No video in selected time period
   at VideoOS.Platform.SDK.Export.DBExporterXpco.StartExport(DateTime start, DateTime end)
   at VideoOS.Platform.Data.DBExporter.StartExport(DateTime start, DateTime end)
   at MilestonePSTools.ExportCommands.StartExport.Export(IExporter exporter) in C:\agent\_work\2\s\src\MilestonePSTools\ExportCommands\StartExport.cs:line 260,MilestonePSTools.ExportCommands.StartExport
```

The verbose output is showing the wrong date, but that might just be due to the UTC offset?:
`VERBOSE: Exporting data from 7/11/2022 5:00:00 AM to 7/11/2022 5:05:00 AM` 

Here is the full verbose output:
```
VERBOSE: Camera: Entrance (South Corridor)
VERBOSE: Switching Environment.CurrentDirectory to C:\Users\vuser\Documents\WindowsPowerShell\Modules\MipSdkRedist\22.1.0\Bin
VERBOSE: Exporting data from 7/11/2022 5:00:00 AM to 7/11/2022 5:05:00 AM
Start-Export : No video in selected time period
At line:1 char:1
+ Start-Export -CameraIDs XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX -StartTi ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (VideoOS.Platform.Data.DBExporter:DBExporter) [Start-Export], NoVideoInTimeSpanMIPException
    + FullyQualifiedErrorId : VideoOS.Platform.NoVideoInTimeSpanMIPException: No video in selected time period
   at VideoOS.Platform.SDK.Export.DBExporterXpco.StartExport(DateTime start, DateTime end)
   at VideoOS.Platform.Data.DBExporter.StartExport(DateTime start, DateTime end)
   at MilestonePSTools.ExportCommands.StartExport.Export(IExporter exporter) in C:\agent\_work\2\s\src\MilestonePSTools\ExportCommands\StartExport.cs:line 260,MilestonePSTools.ExportCommands.StartExport
```

**Comment by jdelaughter** [comment]
Another interesting thing is that when I grab the stats from a cam, they don't appear to be showing the correct info:
`(Get-CameraRecordingStats -Id XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX).recordingstats`

It shows the following output:
```
DeviceId        : XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX
StartTime       : 7/6/2022 12:00:00 AM
EndTime         : 7/13/2022 12:00:00 AM
SequenceCount   : 2
TimeRecorded    : 6.23:58:08.3690000
PercentRecorded : 100
```
However, my retention is set to 61 days, and in the smart client, I can view video prior to 7/6/2022...

**Comment by jdelaughter** [comment]
I also tried it on version `21.2.7` of the module since the milestonepstools website lists that as the current version, but no dice. 

Dying to know what I might be doing wrong.

**Comment by joshooaj** [comment]
Hi @jdelaughter and thanks for opening an issue!

You're right about the timestamps in the verbose log message - any `DateTime` you provide in a cmdlet will be converted to UTC before being sent to Milestone because we "think" almost exclusively in UTC. So as long as your TZ offset is -5 and you intended to export 5 minutes of video starting from midnight local time, then I think your timestamps were correct.

If you _definitely_ have video in that time period, is there any chance you have a ridiculously long GOP length on that camera? The GOP length is the number of frames in a single Group Of Pictures which is a concept associated with MPEG/H264/H265 where a single GOP includes a keyframe, and some number of intermediate B/P frames. By default the recording server usually requests camera streams with a GOP length equal to the frame rate. So if your FPS is 30, your GOP length is 30, which means every 30th frame is a keyframe, and you'll see a keyframe once per second.

The GOP length or "Keyframe interval" or "I-frame interval" can be customized most of the time, and H264+, H265+ "smart codecs" can produce dynamic GOP lengths that change based on the level of activity. With those dynamic GOP lengths it's possible to have one key frame every several minutes instead of once per second, and I'm wondering if the DBExporter class might be sensitive to that.

I haven't looked at that `Get-CameraRecordingStats` cmdlet in a while and don't know off hand why it might give you such incorrect info and it's not likely yours or your system's fault :) Here's another way we can peek at what the Recording Server thinks is available during that time period...

```powershell
$start = Get-Date -Year 2022 -Month 7 -Day 11 -Hour 0 -Minute 0 -Second 0 -Millisecond 0
$end = $start.AddMinutes(5)
$sequences = Select-Camera | Get-SequenceData -StartTime $start -EndTime $end -SequenceType RecordingSequence | Select-Object -ExpandProperty EventSequence
$sequences | Select-Object StartDateTime, EndDateTime
```

By default, `Get-SequenceData` returns unmodified sequences, so for example if a 10-minute recording sequence was already in progress at 12:00am, and it continued for 10 minutes beyond `$end` (which is 12:05am here), then you would see one recording sequence as a result of the above commands, with a `StartDateTime` of 11:50pm the day before, and an `EndDateTime` of 12:15am.

Sometimes it's useful to "crop" the sequence data returned from that command, so if that's ever important to you, you can use `-CropToTimeSpan` and as a result the first and last sequences returned by the command will have their `StartDateTime` and `EndDateTime` constrained to the `StartTime` and `EndTime` values you provide.

If none of this helps, let me know what the output of `Get-SequenceData` is, as that should tell us what the Recording Server thinks. And let me know if Smart Client is able to export the same time period.

Cheers,

Josh
