### ISSUE TITLE
Group API "mistakes"

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#67]
Hello,

I played with device groups and found many little design mistakes, just dumping it all here:

- `Get-DeviceGroup -DeviceCategory Camera -Path /NOT_EXISTING_FOLDER` throws even with `-EA Continue`, it's annoying when using it to test wether a path exists (maybe I missed something).
- `$group | Remove-DeviceGroup` should be allowed.
- `Remove-DeviceGroup -DeviceCategory Camera -Path /Bla; Add-DeviceGroup -DeviceCategory Camera -Path /Bla` does not create the group (you probably don't wait for the task to finish or smth).
- `$group | Add-DeviceGroupMember -DeviceCategory Camera -Device $camera` should be `$cameras | Add-DeviceGroupMember -Group $group`, at least we should not need to specify the DeviceCategory.

**Comment by Silex** [comment]
Unrelated but I wrote this, thought you might find it useful:

``` ps1
function Wait-TaskCompletion {
  param($Task)
  while ($Task.State -ne [VideoOS.Platform.ConfigurationItems.StateEnum]::Error -and $Task.State -ne [VideoOS.Platform.ConfigurationItems.StateEnum]::Success) {
      Sleep -Milliseconds 10
      $Task.UpdateState()
  }
}
```

**Comment by joshooaj** [comment]
The old device group cmdlets were truly bad. They have now been replaced with `*-VmsDeviceGroup` and `*-VmsDeviceGroupMember` cmdlets with aliases and version 22.3.0 is published to PSGallery.

Here are some of the improvements:
- When working with cameras, the "Type" or "DeviceCategory" can be omitted since it is the default device group type.
- Get-DeviceGroup writes an error now instead of throwing when the group doesn't exist, so `-ErrorAction SilentlyContinue` works as expected.
- Remove a group like `Get-VmsDeviceGroup -Path '/Foo' | Remove-VmsDeviceGroup -Confirm:$false -Recurse`. Since device groups can be used in rules, deleting one can have a significant impact, so the ConfirmImpact value is set to high and you need to confirm the removal. If the device group is not empty, the `-Recurse` switch is needed to indicate that all child members should be removed too.
- You can remove and immediately re-add a device group now. I think it was a caching issue before.
- Adding cameras to a device group looks like `New-VmsDeviceGroup -Path '/All the cameras' | Add-VmsDeviceGroupMember -Device (Get-VmsCamera)`

**Comment by Silex** [comment]
Great thanks! 🥳
