### ISSUE TITLE
Add 'Event server and add-ons' to Set-XProtectCertificate?

### ISSUE THREAD

**Issue by jdelaughter** [MilestoneSystemsInc/PowerShellSamples#69]
Would it be possible for you to add the 'Event server and add-ons'  VmsComponent to the Set-XProtectCertificate function?

I found that I can update it by using `Invoke-ServerConfigurator -EnableEncryption -CertificateGroup '7e02e0f5-549d-4113-b8de-bda2c1f38dbf' -Thumbprint $thumbprint` but it could be helpful to add it to the "friendlier" function. Unless there was a technical reason to leave that out?

**Comment by joshooaj** [comment]
Great idea! The only reason it's not there now is probably because it wasn't an option at the time the cmdlet was written. The 'Invoke-ServerConfigurator' cmdlet you used is a more "raw" command wrapping the configurator CLI it works, but it's nice having the clear single-purpose "Set-XProtectCertificate" cmdlet. we'll be sure to update that in the next release :)

**Comment by jdelaughter** [comment]
Awesome, you rock!

**Comment by joshooaj** [comment]
Resolved in 22.3.0 now published to PSGallery!
