### ISSUE TITLE
Authorization Error using Set-XProtectCertificate function

### ISSUE THREAD

**Issue by jdelaughter** [MilestoneSystemsInc/PowerShellSamples#71]
Hey again Josh, in trying to work around issue #70 until it gets addressed, I just copied the `Set-XProtectCertificate` function from the module into a script that the LE cert manager runs. However, it only changes some of the certs. The others fail with the following error:

```
Encryption configuration is applied, but server service(s) registration on the management server failed. The user is not authorized for this action. Go to the Registering servers tab. Select a user with permission and try again.
```
(This is from the output of the `serverconfigurator.exe` that gets called in the `Set-XProtectCertificate` function.)

I've seen this before doing it in the GUI, but not always. This script is running as LOCAL SYSTEM, so I'm not sure how much more permission it could have.

Any clue what might be causing this error?

**Comment by joshooaj** [comment]
Could be a couple things - if you get stuck, you might open a support case with Milestone support and just mention the server configurator CLI without PowerShell/pstools.

When you change encryption settings it also does a new registration with the IDP component on the management server to make sure that succeeds. Registration is done as "current Windows user" so that user must be added to the Administrators role in Milestone.

If the certificate you're applying uses a different DNS name than the Windows machine itself, you need to edit the Registry entry named "BackConnectionHostNames" which is an obscure Microsoft security hack that prevents you from authenticating as current user against a DNS name that doesn't match the computer name. I had to do this to get a Let's Encrypt certificate to work for server encryption for example.

When doing automation from PowerShell, something else to keep in mind is that you can't do a "double hop" and pass "current user" credentials during registration if you're in a PSRemoting session. To work around this, I use Register-ScheduledJob to create and run an elevated scheduled task, providing the credentials when creating the task. Then I call server configurator from within the script block executed by the scheduled task. But this is only necessary if you're PSRemoting into your servers and invoking server configurator there.
