### ISSUE TITLE
Get-VmsCamera returns camera where hardware is disabled

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#74]
Hello,

I think this is more a bug in the MIPSDK but if you disable an entire hardware, its "enabled" cameras are still returned with `Get-VmsCamera`.

**Comment by joshooaj** [comment]
Yeah that's one of those things I know about and code for because I know it, but it would be better if there was a performant way to return the expected results rather than know about, and code around the behavior.

The issue is that a hardware object can be enabled or disabled, and a camera (or mic, speaker, I/O, or metadata) can be enabled or disabled. In the Management Client, there is some UI logic that shows a "disabled" icon on the camera when the hardware is disabled, but technically according to the Configuration API, the camera is still "enabled".

The camera is not enabled in any other way that I'm aware of - the recording server certainly believes the camera and all other sibling devices are disabled when the parent hardware object is disabled.

With Configuration API, if we want to only return enabled cameras if both the hardware and the camera are enabled, then before we can return a camera we have to "look up" at the hardware to see if it is enabled.

This can be done really fast if Get-VmsCamera is being called with one or more Hardware objects because we already have the hardware objects. But if we're just calling `Get-VmsCamera` without any parameters, then we're using a Configuration API class called "QueryItems" to find all cameras by name, with a few filters (name, description, and enabled-state). To give the expected results with this QueryItems method, we would have to get an instance of the parent Hardware item to check its enabled-state before returning an enabled camera and that would be an extra API call for each camera instance.

It's common to disable the hardware and to later enable it, and nobody wants to have to individually re-enable each child device on the hardware so it's probably best that we maintain the enabled-state for the child devices in the SDK. I don't like that you can't know from the Camera object itself whether it is effectively disabled by a disabled parent hardware object but I'm not sure the best way for the SDK to surface that information.

One thing I could do in the `Get-VmsCamera` cmdlet is to check against `[VideoOS.Platform.SDK.Environment]::GetDisabledDevices((Get-Site).FQID.ObjectId)` and avoid returning any of the devices in that list if their FQID.ObjectId matches cameras about to be returned. Thoughts?

**Comment by Silex** [comment]
Well I agree that it'd kill performance, I also think the situation sucks 🤷‍♂️

Maybe the best we can do is document it and provide a workaround...

Now that I think about it maybe an additional flag could do it, e.g `Get-VmsCamera -CheckHardwareEnabled $true`, which would make it clear extra operations are done and it's slower.

**Comment by joshooaj** [comment]
So I've managed to handle this without much of a performance hit as far as I can tell, and it requires no extra parameters. On a test system with 118 enabled cameras, it takes just under 500ms to retrieve the list of enabled cameras the first time and about 12ms on average after that based on 100 executions.

Initially I thought I'd use `[VideoOS.Platform.SDK.Environment]::GetDisabledDevices((Get-Site).FQID.ObjectId)` but it seems like this isn't reliable - might be that it only works if you are in the Administrators role. Something I need to follow up on to understand. So instead of getting a list of disabled devices, I'm getting a list of _enabled_ devices by pulling from `[VideoOS.Platform.Configuration]::Instance.GetItemsByKind([VideoOS.Platform.Kind]::Camera, [VideoOS.Platform.ItemHierarchy]::SystemDefined)`.

So now before returning a camera, the cmdlet will check the `EnableFilter` value and see if the camera is present in the list of enabled cameras. It will also allow folks running on 2020 R1 and earlier to run `Get-VmsCamera` without any parameters, and it will fall back to running `Get-Hardware | Get-VmsCamera` instead of throwing an error because the Configuration API server-side query service isn't available.

We should be pushing the 22.3.0 module to PSGallery this week 😁
