### ISSUE TITLE
Remove-VmsDeviceGroup issues

### ISSUE THREAD

**Issue by jamesangi** [MilestoneSystemsInc/PowerShellSamples#77]
I'm trying to adjust one of my scripts to use the new Vms* cmdlets for managing device groups as the parameters/semantics have changed.  I got most everything working again (and the defaults in the new cmdlets are nice... Camera is the default type, and if you create a group that already exists it just returns that group instead of an error, etc).

Remove-VmsDeviceGroup is giving me some headaches though:
`
PS C:\Users\atg-user> Connect-ManagementServer -ServerAddress "http://wps-it-cctv"
PS C:\Users\atg-user> New-VmsDeviceGroup -Name "DeleteMe"

DisplayName ItemCategory Path                                              ParentPath
----------- ------------ ----                                              ----------
DeleteMe    Item         CameraGroup[a4eec378-be88-4aac-accf-e68cc798606e] /CameraGroupFolder

PS C:\Users\atg-user> Get-VmsDeviceGroup -Name "DeleteMe" |Remove-VmsDeviceGroup

Confirm
Are you sure you want to perform this action?
Performing the operation "Delete" on target "DeleteMe".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): Y
The property 'Value' cannot be found on this object. Verify that the property exists and can be set.
At C:\Program Files\WindowsPowerShell\Modules\MilestonePSTools\22.3.0\MilestonePSTools.psm1:5656 char:17
+ ...             ($invokeInfo.Properties | Where-Object Key -eq 'RemoveMem ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : PropertyNotFound

PS C:\Users\atg-user> Get-VmsDeviceGroup -Name "DeleteMe"
Get-VmsDeviceGroup : No Camera group found with the name 'DeleteMe'
At line:1 char:1
+ Get-VmsDeviceGroup -Name "DeleteMe"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,Get-VmsDeviceGroup
`

So, two things:
1) It asks for a confirmation even without the -Confirm parameter
2) It has a bizarre error, but it actually does remove the group.

**Comment by jamesangi** [comment]
I just realized I only had tried this on 2019 R1... so I just tested against 2022 R1. The confirmation issue exists on both 2019/2022, but the weird error only pops up on 2019.

**Comment by joshooaj** [comment]
Thanks @jamesangi,

The way the whole confirm thing works in PowerShell is a little confusing but I'm pretty sure you're seeing the expected behavior. The `ConfirmImpact` value for this cmdlet is set to "High" because deleting device groups can cause interruption to recordings, so you'll always be prompted for confirmation unless you explicitly disable confirmation.

Check out the [`$ConfirmPreference`](https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_preference_variables?view=powershell-5.1#confirmpreference) documentation for more info, but the gist is that when you want to avoid confirmation for a specific command, you can invoke it like `Remove-VmsDeviceGroup -Confirm:$false`. And if you want to avoid confirmation for all commands, you can set `$ConfirmPreference = 'None'`.

That error is something we can sort out though. The way device groups are removed is to invoke the `RemoveDeviceGroup` method on the parent device group folder. We then supply values for the `RemoveMembers` and `ItemSelection` parameters presented to us by the management server. It looks like on 2019 R1 there is no `RemoveMembers` parameter to fill in, but the cmdlet tries anyway and that's why you get that odd error.

We can change the way this is set from...

```powershell
($invokeInfo.Properties | Where-Object Key -eq 'RemoveMembers').Value = $Recurse.ToString()
```

to something like...

```powershell
if ($prop = ($invokeInfo.Properties | Where-Object Key -eq 'RemoveMembers')) {
  $prop.Value = $Recurse.ToString()
}
```

though I'm not sure what that means for 2019 systems where you want to recursively remove subgroups and device group members if there's no `RemoveMembers` property for us to communicate that intention. On your 2019 system you said it does delete the device group - does it still delete the group if it has cameras in it or a subgroup with cameras in it?

**Comment by jamesangi** [comment]
No I should've been more specific... it deletes an empty group (but still shows the property error).  When deleting a group that contains things it gives a longer error and does not remove anything.  I just realize github kind of mangled the error I tried to put in a code block.  Let me know if you need the exact messages.

Also, were you suggesting I try the code change you posted?  I'm happy to test I'm just not sure where to change that.  I do have development experience, including with the MIP SDK... just not with powershell.

**Comment by joshooaj** [comment]
I know this is a very old issue now, I just wanted to share that I cannot reproduce any unexpected behavior as of MilestonePSTools 23.2.1. See the screenshot below where I get an expected error when trying to delete a camera group with subgroups/cameras without the `-Recurse` switch. When I add `-Recurse`, the group is removed without error. And the confirmation can be silenced when adding `-Confirm:$false` like so `Remove-VmsDeviceGroup -Recurse -Confirm:$false`.

Please do open a new issue if you encounter strange behavior, and include the MilestonePSTools and Management Server versions for reference. Thanks!

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/7669972/eabe57e5-f8e8-46f8-98f1-5fe0432a6882)
