### ISSUE TITLE
Set-VmsCameraStream bug when using codec name

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#79]
Hello,

I found a nice bug with `Set-VmsCameraStream`:

``` ps1
# $s is a Camera Stream object from an Axis camera
PS C:\Users\pv> $s.ValueTypeInfo.Codec

TranslationId                        Name  Value
-------------                        ----  -----
76c84c36-d7f8-47fe-9cd2-8ffb1ef85760 MJPEG jpeg
cf1e23d9-701a-4407-bdfd-997f2d77483f H.264 h264
d58b0c16-159b-4fa8-b62a-79b244591b40 H.265 h265

# 1
PS C:\Users\pv> $s | Set-VmsCameraStream -Settings @{ Codec = 'H.264' } -Verbose
VERBOSE: Performing the operation "Changing Codec from h265 to H.264" on target "Video stream 1 on BCV1-TV-00-C46".
VERBOSE: Performing the operation "Save changes" on target "Video stream 1 on BCV1-TV-00-C46".

# 2
PS C:\Users\pv> $s | Set-VmsCameraStream -Settings @{ Codec = 'h264' } -Verbose
VERBOSE: Performing the operation "Changing Codec from H.264 to h264" on target "Video stream 1 on BCV1-TV-00-C46".
VERBOSE: Performing the operation "Save changes" on target "Video stream 1 on BCV1-TV-00-C46".
```

When doing `1`, it looks like it works, the interface correctly displays "H. 264" in the Management Client BUT what happens is that the MJPEG stream is used, you can verify this with the Diagnostic Overlay in the Smart Client.

When doing `2`, the real h264 codec is used and everything works normally.

For the context we couldn't understand why suddenly some cameras were using heaps of storage, and why doing "replace hardware" fixed it... and eventually why simply changing a setting and changing it back also fixed it... Now it makes sense: when a wrong value is stored what is really used is the first item and that's why we ended up with MJPEG instead of h264, but this was really hard to notice.

I guess the bugs are 50% MilestonePSTools for having a validation logic error and 50% MIPSDK for allowing wrong values to be stored AND displaying them anyway in the Management Client.

**Comment by joshooaj** [comment]
Great find, thank you @Silex!

MilestonePSTools isn't doing much here to prevent you from trying to apply an invalid setting and I tend to put the responsibility on the VMS to throw a validation exception. For some reason the VMS is accepting the codec display name value instead of the raw value and getting itself into a weird state where the UI shows the desired codec but the recording server probably defaults to whatever the first codec in the list is when there's no exact match.

I'll open a bug report with the SDK team so they can look into it and I'll also look into possibly adding some extra validation, though I'm hesitant to add my own validation layer when the VMS has it's own and it incorrectly says "H.264" is okay in this case.

**Comment by joshooaj** [comment]
I _finally_ got around to reporting this. It comes down to a MIP SDK bug / behavior issue rather than a MilestonePSTools issue though so I'll close this.

Make sure to use the "raw values" when updating device settings and not the display values as a general rule. Still, it's not great that the UI says the codec is H.264 when it's JPEG, so hopefully that'll be an easy fix in a future release.
