### ISSUE TITLE
Add-VmsRoleMember does not work for local accounts when managing remote server

### ISSUE THREAD

**Issue by Silex** [MilestoneSystemsInc/PowerShellSamples#84]
Hello,

I'm not sure if this is something you should fix but it's interesting:

``` ps1
$Server = 'someserver'
$Account = '{0}\someaccount' -f $Server

Connect-ManagementServer $Server
$role = Get-VmsRole | Select -First 1

# Not working
$role | Add-VmsRoleMember -AccountName $Account

# Working
$ConvertToSid = & (Get-Module MilestonePSTools) { (Get-Command ConvertTo-Sid).Definition }
$ConvertToSid = [ScriptBlock]::Create($ConvertToSid)
$sid = Invoke-Command -ComputerName $Server $ConvertToSid -ArgumentList $Account
$role | Add-VmsRoleMember -Sid $sid
```

It's logical because `ConvertTo-Sid` runs locally yet we are trying to configure a remote server, so the "local account" is not present locally and it fails.

As you see I had to trick around to forcefully expose `ConvertTo-Sid` in order to run it remotely.

**Comment by joshooaj** [comment]
Good discussion to have and I'm not sure what the best answer is. I think Management Client demonstrates the same issue. The management server doesn't provide us with an API for resolving Windows/AD user identities. All the SDK provides is a way to add users to a role by SID. Figuring out the SID is an exercise for the user.

I'm quite fond of using an OpenId Connect identity provider like Azure AD, Okta, Auth0 and others. Then instead of adding users or groups to roles and worrying about SIDs, you add one or more claim names/values to the roles and then make sure the users in your identity management platform have the appropriate claims. The last release has new cmdlets for working with those properties like Get/Add/Remove-VmsRoleClaim.
