### ISSUE TITLE
Limit scans in Extend_Get-CameraReport.ps1

### ISSUE THREAD

**Issue by saw0ne** [MilestoneSystemsInc/PowerShellSamples#86]
Great report! Is there a way(parm) to limit the number of cameras it scans? The test hangs if run with several 100 cameras.

Keep up the great work!

Extend_Get-CameraReport.ps1

**Comment by Tarterman** [comment]
If you need the extended functionality that Extend_Get-CameraReport.ps1 offers (where it does a Test-NetConnection to any camera lists as Not Responding), you could edit line 15 to the following which would limit it to a single Recording Server instead of all Recording Servers.

```
$rs = Get-RecordingServer -Name "recording_server_name"
$report = Get-VmsCameraReport -RecordingServer $rs
```

You could also add parameters instead so you could specify the recording server name when you call the script.  The currently the only way to limit the number of cameras.
