### ISSUE TITLE
Get-VmsCameraStream shows that no cameras are configured for recording in 2023 R2

### ISSUE THREAD

**Issue by Tarterman** [MilestoneSystemsInc/PowerShellSamples#91]
I'm assuming this has to do with the change we did for adaptive playback.  Here is the output for Get-VmsCameraStream in 2023 R2.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/42384254/e1cb3a87-9a52-435c-acb0-a33d9896b9ba)

Here is the Management Client settings for that camera.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/42384254/80e69783-23e0-4752-b899-7122d6ace7da)

**Comment by joshooaj** [comment]
Thanks @Tarterman, the stream settings cmdlets will need some work with the introduction of adaptive playback for sure. First step will be to update to the 23.2 SDK, and then we'll need to figure out how to make these cmdlets work with 2023 R2 as well as previous versions without adaptive playback support.

**Comment by joshooaj** [comment]
MilestonePSTools v23.2.1 is published and includes changes to the `Get-VmsCameraStream` and `Set-VmsCameraStream` cmdlets which should not be breaking changes.

In the screenshot below we see the before/after when enabling a second stream to record to the secondary recording track.

One thing to note is that after enabling adaptive playback this way, you'll see the old "Recorded" property is `$true` on both streams. I thought it should show this way because they are indeed both being recorded. However, the old deprecated "Record" property on the `StreamUsageChildItem` MIP SDK objects will only be true for the primary recorded stream which makes sense for compatibility.

But to avoid breaking existing scripts, the `Get-VmsCameraStream -Recorded` cmdlet will only return the primary recorded stream. That way if you have existing code that needs to retrieve the traditional "main recorded stream" which has, until now, always been the only recorded stream, your scripts should still behave the same on both 2023 R2 and on earlier versions.

Going forward, it's a good idea to switch to using `Get-VmsCameraStream -RecordingTrack Primary` to be explicit about which recorded stream to retrieve. Again, this will behave the same on 2023 R2 and on earlier versions predating the new adaptive playback feature.

![image](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/7669972/b1273762-569e-469d-8bee-7c2987b0fa9e)
