### ISSUE TITLE
Visual Studio - Powershell extension does not work?

### ISSUE THREAD

**Issue by CarlOscar002** [MilestoneSystemsInc/PowerShellSamples#93]
Hi,

Not an issue with the module I assume, but if possible - can I get some tips to fix my issue?
I have Visual Studio Code and the Powershell extension, but when I try to connect to a managementserver I get the following error message: Method not found: 'Void System.ServiceModel.HttpBindingBase.set_HostNameComparisonMode(System.ServiceModel.HostNameComparisonMode)'.

If I use ISE it works as usually.
I have the latest MPStools installed and latest MipSdk.

Kind regards,

**Comment by Tarterman** [comment]
@CarlOscar002, Visual Studio Code defaults to using PowerShell 7 if it is installed on the machine.  The error you are seeing is what happens if you try and use MilestonePSTools in PowerShell 7.  I can't remember how to do it but there is a way to switch the terminal in VS Code from PowerShell 7 to PowerShell 5.1 which is what is required for MilestonePSTools.

**Comment by joshooaj** [comment]
Yep, since the Milestone .NET SDK is based on .NET Framework, you'll need to use Windows Powershell (x64) aka "PowerShell 5.1" when working with the module.

You can always run `$PSVersionTable` to see what version of PowerShell the current terminal is using.

I added `"powershell.powerShellDefaultVersion": "Windows PowerShell (x64)"` to my settings.json file in vscode since I most often work with Windows Powershell, and you can customize the settings for your workspace in vscode by creating a .vscode folder at the root of the workspace, and a settings.json file inside. Inside that file, you can add any specific customizations you want to apply for that project which comes in even more handy when working on the same project with multiple people, as it allows everyone to share similar code formatting rules and linting settings, etc.

You can always change which PowerShell language server is used by the integrated powershell terminal in vscode regardless of the defaults. And you can open up different/additional terminal sessions in vscode by clicking on the little down arrow next to the "+" in the top-right of the bottom pane of a default vscode layout.

![Code_GltY44ihaJ](https://github.com/MilestoneSystemsInc/PowerShellSamples/assets/7669972/8ff6928a-cefd-4828-b9e7-dfd366bf40b8)

**Comment by CarlOscar002** [comment]
Hi,

Sorry for a late response, vacation time 😄 
But thanks a lot to both of you!

Kind regards,
