### ISSUE TITLE
Question about Get-VmsCameraReport

### ISSUE THREAD

**Issue by iperry-indigex** [MilestoneSystemsInc/PowerShellSamples#97]
We monitor our cameras' recording status via the Get-VmsCameraReport -IncludeReportingStats cmdlet. A few days ago, at exactly midnight, we had the stats for all the cameras drop by ~5% simultaneously. Does this function run on a rolling schedule, or at midnight does it completely disregard the stats from day 8?

**Comment by joshooaj** [comment]
Hi @iperry-indigex,

The logic for `-IncludeRecordingStats` uses the `Get-SequenceData` cmdlet with a StartTime set to 7 days prior to midnight of the current day, and an end time of midnight of the current day (both based on the local timezone of the PowerShell session).

Say you run the report at midnight on August 17th, it might be possible that the start and end times are calculated at slightly different moments such that the StartTime is 7 days prior to 12:00AM on the 17th as expected, while the EndTime is calculated as 12:00AM on the 16th instead of the 17th.

I don't know if that could be the cause, but looking at how the start/end times are determined, there's room for improvement to eliminate that possibility.

Actually, looking at it some more, the start/end time used to generate the information will be slightly different for every camera since for every camera id, it's calling `Get-Date` to generate timestamps for start/endtime.

What I'll do is change the function to calculate an "EndTime" value _once_, and derive a "StartTime" value _once_ by subtracting 7 days from EndTime. That way there's zero opportunity for the start and end time to be anything different than 7 days exactly, and the calls to `Get-SequenceData` will use the exact same timestamps for every camera. I'll also toss out the `.Date` bits since I don't think it matters if the reports starts 7 days from "now" vs "the beginning of the day".

## Current Code

```powershell
$recordingStatsScript = {
    param(
        [guid]$Id,
        [datetime]$StartTime,
        [datetime]$EndTime,
        [string]$SequenceType
    )

    $sequences = Get-SequenceData -Path "Camera[$Id]" -SequenceType $SequenceType -StartTime $StartTime -EndTime $EndTime -CropToTimeSpan
    $recordedMinutes = $sequences | Foreach-Object {
        ($_.EventSequence.EndDateTime - $_.EventSequence.StartDateTime).TotalMinutes
        } | Measure-Object -Sum | Select-Object -ExpandProperty Sum
    [pscustomobject]@{
        DeviceId = $Id
        StartTime = $StartTime
        EndTime = $EndTime
        SequenceCount = $sequences.Count
        TimeRecorded = [timespan]::FromMinutes($recordedMinutes)
        PercentRecorded = [math]::Round(($recordedMinutes / ($EndTime - $StartTime).TotalMinutes * 100), 1)
    }
}
$recordingStatsJobs = $ids | Foreach-Object {
    $jobRunner.AddJob($recordingStatsScript, @{Id = $_; StartTime = (Get-Date).Date.AddDays(-7); EndTime = (Get-Date).Date; SequenceType = 'RecordingSequence'})
}
```

## New Code

```powershell
$recordingStatsScript = {
    param(
        [guid]$Id,
        [datetime]$StartTime,
        [datetime]$EndTime,
        [string]$SequenceType
    )

    $sequences = Get-SequenceData -Path "Camera[$Id]" -SequenceType $SequenceType -StartTime $StartTime -EndTime $EndTime -CropToTimeSpan
    $recordedMinutes = $sequences | Foreach-Object {
        ($_.EventSequence.EndDateTime - $_.EventSequence.StartDateTime).TotalMinutes
        } | Measure-Object -Sum | Select-Object -ExpandProperty Sum
    [pscustomobject]@{
        DeviceId = $Id
        StartTime = $StartTime
        EndTime = $EndTime
        SequenceCount = $sequences.Count
        TimeRecorded = [timespan]::FromMinutes($recordedMinutes)
        PercentRecorded = [math]::Round(($recordedMinutes / ($EndTime - $StartTime).TotalMinutes * 100), 1)
    }
}
$endTime = Get-Date
$startTime = $endTime.AddDays(-7)
$recordingStatsJobs = $ids | Foreach-Object {
    $jobRunner.AddJob($recordingStatsScript, @{Id = $_; StartTime = $startTime; EndTime = $endTime; SequenceType = 'RecordingSequence'})
}
```

**Comment by joshooaj** [comment]
Hi @iperry-indigex,

MilestonePSTools v23.2.1 is available with this change - let me know if you keep seeing larger than normal fluctuations in % time recorded day over day.
